/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type StreaksRankingsRequestType = "active" | "longest";
export declare const StreaksRankingsRequestType: {
    readonly Active: "active";
    readonly Longest: "longest";
};
