/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         user: {
 *             email: "user@example.com",
 *             name: "User",
 *             tz: "Europe/London",
 *             deviceTokens: ["token1", "token2"],
 *             subscribeToEmails: true,
 *             attributes: {
 *                 "department": "engineering",
 *                 "role": "developer"
 *             },
 *             id: "user-id"
 *         }
 *     }
 */
export interface AchievementsCompleteRequest {
    /** The user that completed the achievement. */
    user: TrophyApi.UpsertedUser;
}
