/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         userAttributes: "plan-type:premium,region:us-east"
 *     }
 */
export interface AchievementsAllRequest {
    /**
     * Optional colon-delimited user attributes in the format attribute:value,attribute:value. Only achievements accessible to a user with the provided attributes will be returned.
     */
    userAttributes?: string;
}
