/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         user: {
 *             id: "user-id"
 *         }
 *     }
 */
export interface AchievementsCompleteRequest {
    /** The user that completed the achievement. */
    user: TrophyApi.UpsertedUser;
}
