/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../../../environments";
import * as core from "../../../../../../../../core";
import * as TrophyApi from "../../../../../../..";
export declare namespace Boosts {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Boosts {
    protected readonly _options: Boosts.Options;
    constructor(_options: Boosts.Options);
    /**
     * Create points boosts for multiple users.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.boosts.create({
     *         systemKey: "xp",
     *         boosts: [{
     *                 userId: "user-123",
     *                 name: "Double XP Weekend",
     *                 start: "2024-01-01",
     *                 end: "2024-01-03",
     *                 multiplier: 2
     *             }, {
     *                 userId: "user-456",
     *                 name: "Holiday Bonus",
     *                 start: "2024-12-25",
     *                 multiplier: 1.5,
     *                 rounding: TrophyApi.admin.points.CreatePointsBoostsRequestBoostsItemRounding.Up
     *             }]
     *     })
     */
    create(request: TrophyApi.admin.points.CreatePointsBoostsRequest, requestOptions?: Boosts.RequestOptions): Promise<TrophyApi.CreatePointsBoostsResponse>;
    /**
     * Archive multiple points boosts by ID.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     *
     * @example
     *     await trophyApi.admin.points.boosts.batchArchive({})
     */
    batchArchive(request?: TrophyApi.admin.points.BoostsBatchArchiveRequest, requestOptions?: Boosts.RequestOptions): Promise<TrophyApi.ArchivePointsBoostsResponse>;
    /**
     * Archive a points boost by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     *
     * @example
     *     await trophyApi.admin.points.boosts.archive("id")
     */
    archive(id: string, requestOptions?: Boosts.RequestOptions): Promise<void>;
}
