"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrophyApiEnvironment = void 0;
exports.TrophyApiEnvironment = {
    Default: "https://app.trophy.so/api",
};
