/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AchievementResponse: core.serialization.ObjectSchema<serializers.AchievementResponse.Raw, TrophyApi.AchievementResponse>;
export declare namespace AchievementResponse {
    interface Raw {
        id: string;
        name: string;
        trigger: serializers.AchievementResponseTrigger.Raw;
        description?: string | null;
        badgeUrl?: string | null;
        key?: string | null;
        streakLength?: number | null;
        metricId?: string | null;
        metricValue?: number | null;
        metricName?: string | null;
        userAttributes?: serializers.AchievementResponseUserAttributesItem.Raw[] | null;
        eventAttribute?: serializers.AchievementResponseEventAttribute.Raw | null;
    }
}
