/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AchievementResponseEventAttribute: core.serialization.ObjectSchema<serializers.AchievementResponseEventAttribute.Raw, TrophyApi.AchievementResponseEventAttribute>;
export declare namespace AchievementResponseEventAttribute {
    interface Raw {
        key: string;
        value: string;
    }
}
