/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AchievementResponse: core.serialization.Schema<serializers.AchievementResponse.Raw, TrophyApi.AchievementResponse>;
export declare namespace AchievementResponse {
    type Raw = serializers.MetricAchievementResponse.Raw | serializers.StreakAchievementResponse.Raw | serializers.ApiAchievementResponse.Raw;
}
