/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminLeaderboardRankBy: core.serialization.Schema<serializers.AdminLeaderboardRankBy.Raw, TrophyApi.AdminLeaderboardRankBy>;
export declare namespace AdminLeaderboardRankBy {
    type Raw = "metric" | "streak" | "points";
}
