/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminIssueSeverity: core.serialization.Schema<serializers.AdminIssueSeverity.Raw, TrophyApi.AdminIssueSeverity>;
export declare namespace AdminIssueSeverity {
    type Raw = "error" | "warning";
}
