/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminAttributeType: core.serialization.Schema<serializers.AdminAttributeType.Raw, TrophyApi.AdminAttributeType>;
export declare namespace AdminAttributeType {
    type Raw = "user" | "event";
}
