/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsSystemBadge: core.serialization.ObjectSchema<serializers.AdminPointsSystemBadge.Raw, TrophyApi.AdminPointsSystemBadge>;
export declare namespace AdminPointsSystemBadge {
    interface Raw {
        url: string;
    }
}
