/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminTenant: core.serialization.ObjectSchema<serializers.AdminTenant.Raw, TrophyApi.AdminTenant>;
export declare namespace AdminTenant {
    interface Raw {
        id: string;
        customerId: string;
        name: string;
        status: serializers.AdminTenantStatus.Raw;
        created: string;
        updated: string;
    }
}
