/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsTriggerType: core.serialization.Schema<serializers.AdminPointsTriggerType.Raw, TrophyApi.AdminPointsTriggerType>;
export declare namespace AdminPointsTriggerType {
    type Raw = "metric" | "achievement" | "streak" | "time" | "user_creation";
}
