/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsBoostStatus: core.serialization.Schema<serializers.AdminPointsBoostStatus.Raw, TrophyApi.AdminPointsBoostStatus>;
export declare namespace AdminPointsBoostStatus {
    type Raw = "active" | "scheduled" | "finished";
}
