/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsTrigger: core.serialization.ObjectSchema<serializers.AdminPointsTrigger.Raw, TrophyApi.AdminPointsTrigger>;
export declare namespace AdminPointsTrigger {
    interface Raw {
        id: string;
        type: serializers.AdminPointsTriggerType.Raw;
        points: number;
        status: serializers.AdminPointsTriggerStatus.Raw;
        userAttributes: serializers.AdminPointsTriggerUserAttributesItem.Raw[];
        metricId?: string | null;
        metricThreshold?: number | null;
        eventAttributes: serializers.AdminPointsTriggerEventAttributesItem.Raw[];
        achievementId?: string | null;
        streakLength?: number | null;
        timeUnit?: serializers.AdminPointsTriggerTimeUnit.Raw | null;
        timeInterval?: number | null;
        blockIfOutOfPoints: boolean;
    }
}
