/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminIssue: core.serialization.ObjectSchema<serializers.AdminIssue.Raw, TrophyApi.AdminIssue>;
export declare namespace AdminIssue {
    interface Raw {
        userId?: string | null;
        boostId?: string | null;
        index?: number | null;
        severity: serializers.AdminIssueSeverity.Raw;
        message: string;
    }
}
