/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsLevelBadge: core.serialization.ObjectSchema<serializers.AdminPointsLevelBadge.Raw, TrophyApi.AdminPointsLevelBadge>;
export declare namespace AdminPointsLevelBadge {
    interface Raw {
        url: string;
    }
}
