/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsTriggerTimeUnit: core.serialization.Schema<serializers.AdminPointsTriggerTimeUnit.Raw, TrophyApi.AdminPointsTriggerTimeUnit>;
export declare namespace AdminPointsTriggerTimeUnit {
    type Raw = "hours" | "days";
}
