/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsBoost: core.serialization.ObjectSchema<serializers.AdminPointsBoost.Raw, TrophyApi.AdminPointsBoost>;
export declare namespace AdminPointsBoost {
    interface Raw {
        id: string;
        name: string;
        status: serializers.AdminPointsBoostStatus.Raw;
        start: string;
        end?: string | null;
        multiplier: number;
        rounding: serializers.AdminPointsBoostRounding.Raw;
        userId?: string | null;
        userAttributes?: serializers.AdminPointsBoostUserAttributesItem.Raw[] | null;
    }
}
