/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminTenantStatus: core.serialization.Schema<serializers.AdminTenantStatus.Raw, TrophyApi.AdminTenantStatus>;
export declare namespace AdminTenantStatus {
    type Raw = "active" | "archived";
}
