/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminPointsTriggerEventAttributesItem: core.serialization.ObjectSchema<serializers.AdminPointsTriggerEventAttributesItem.Raw, TrophyApi.AdminPointsTriggerEventAttributesItem>;
export declare namespace AdminPointsTriggerEventAttributesItem {
    interface Raw {
        attributeId: string;
        attributeValue: string;
    }
}
