/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminLeaderboardRunUnit: core.serialization.Schema<serializers.AdminLeaderboardRunUnit.Raw, TrophyApi.AdminLeaderboardRunUnit>;
export declare namespace AdminLeaderboardRunUnit {
    type Raw = "day" | "month" | "year";
}
