/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const AdminLeaderboardStatus: core.serialization.Schema<serializers.AdminLeaderboardStatus.Raw, TrophyApi.AdminLeaderboardStatus>;
export declare namespace AdminLeaderboardStatus {
    type Raw = "active" | "inactive";
}
