/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ApiAchievementResponse: core.serialization.ObjectSchema<serializers.ApiAchievementResponse.Raw, TrophyApi.ApiAchievementResponse>;
export declare namespace ApiAchievementResponse {
    interface Raw extends serializers.BaseAchievementResponse.Raw {
        trigger: string;
    }
}
