/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const BulkStreakResponse: core.serialization.Schema<serializers.BulkStreakResponse.Raw, TrophyApi.BulkStreakResponse>;
export declare namespace BulkStreakResponse {
    type Raw = serializers.BulkStreakResponseItem.Raw[];
}
