/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const BulkInsertIssueLevel: core.serialization.Schema<serializers.BulkInsertIssueLevel.Raw, TrophyApi.BulkInsertIssueLevel>;
export declare namespace BulkInsertIssueLevel {
    type Raw = "error" | "warning";
}
