/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CompletedAchievementResponse: core.serialization.ObjectSchema<serializers.CompletedAchievementResponse.Raw, TrophyApi.CompletedAchievementResponse>;
export declare namespace CompletedAchievementResponse {
    interface Raw extends serializers.AchievementResponse.Raw {
        achievedAt: string;
    }
}
