/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateMetricRequestItemUnitType: core.serialization.Schema<serializers.CreateMetricRequestItemUnitType.Raw, TrophyApi.CreateMetricRequestItemUnitType>;
export declare namespace CreateMetricRequestItemUnitType {
    type Raw = "number" | "currency";
}
