/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsBoostRequestItem: core.serialization.ObjectSchema<serializers.CreatePointsBoostRequestItem.Raw, TrophyApi.CreatePointsBoostRequestItem>;
export declare namespace CreatePointsBoostRequestItem {
    interface Raw {
        userId?: string | null;
        name: string;
        start: string;
        end?: string | null;
        multiplier: number;
        rounding?: serializers.CreatePointsBoostRequestItemRounding.Raw | null;
        userAttributes?: serializers.CreatePointsBoostRequestItemUserAttributesItem.Raw[] | null;
    }
}
