/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatedMetricUnitType: core.serialization.Schema<serializers.CreatedMetricUnitType.Raw, TrophyApi.CreatedMetricUnitType>;
export declare namespace CreatedMetricUnitType {
    type Raw = "number" | "currency";
}
