/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateAttributesResponse: core.serialization.ObjectSchema<serializers.CreateAttributesResponse.Raw, TrophyApi.CreateAttributesResponse>;
export declare namespace CreateAttributesResponse {
    interface Raw {
        created: serializers.AdminAttribute.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
