/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateLeaderboardRequestItem: core.serialization.ObjectSchema<serializers.CreateLeaderboardRequestItem.Raw, TrophyApi.CreateLeaderboardRequestItem>;
export declare namespace CreateLeaderboardRequestItem {
    interface Raw {
        name: string;
        key: string;
        description?: string | null;
        status: serializers.CreateLeaderboardRequestItemStatus.Raw;
        rankBy: serializers.CreateLeaderboardRequestItemRankBy.Raw;
        metricId?: string | null;
        pointsSystemId?: string | null;
        maxParticipants?: number | null;
        start: string;
        end?: string | null;
        breakdownAttributes?: string[] | null;
        runUnit?: serializers.CreateLeaderboardRequestItemRunUnit.Raw | null;
        runInterval?: number | null;
    }
}
