/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatedPointsBoost: core.serialization.ObjectSchema<serializers.CreatedPointsBoost.Raw, TrophyApi.CreatedPointsBoost>;
export declare namespace CreatedPointsBoost {
    interface Raw {
        id: string;
        name: string;
        start: string;
        end?: string | null;
        multiplier: number;
        rounding: serializers.CreatedPointsBoostRounding.Raw;
        userId: string;
    }
}
