/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsBoostsRequest: core.serialization.Schema<serializers.CreatePointsBoostsRequest.Raw, TrophyApi.CreatePointsBoostsRequest>;
export declare namespace CreatePointsBoostsRequest {
    type Raw = serializers.CreatePointsBoostsRequestItem.Raw[];
}
