/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsLevelsRequestItem: core.serialization.ObjectSchema<serializers.CreatePointsLevelsRequestItem.Raw, TrophyApi.CreatePointsLevelsRequestItem>;
export declare namespace CreatePointsLevelsRequestItem {
    interface Raw {
        name: string;
        key: string;
        points: number;
        description?: string | null;
        badge?: serializers.CreatePointsLevelsRequestItemBadge.Raw | null;
    }
}
