/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateLeaderboardRequestItemRankBy: core.serialization.Schema<serializers.CreateLeaderboardRequestItemRankBy.Raw, TrophyApi.CreateLeaderboardRequestItemRankBy>;
export declare namespace CreateLeaderboardRequestItemRankBy {
    type Raw = "metric" | "streak" | "points";
}
