/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateLeaderboardRequestItemRunUnit: core.serialization.Schema<serializers.CreateLeaderboardRequestItemRunUnit.Raw, TrophyApi.CreateLeaderboardRequestItemRunUnit>;
export declare namespace CreateLeaderboardRequestItemRunUnit {
    type Raw = "day" | "month" | "year";
}
