/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsSystemsRequest: core.serialization.Schema<serializers.CreatePointsSystemsRequest.Raw, TrophyApi.CreatePointsSystemsRequest>;
export declare namespace CreatePointsSystemsRequest {
    type Raw = serializers.CreatePointsSystemRequestItem.Raw[];
}
