/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateTenantsResponse: core.serialization.ObjectSchema<serializers.CreateTenantsResponse.Raw, TrophyApi.CreateTenantsResponse>;
export declare namespace CreateTenantsResponse {
    interface Raw {
        created: serializers.AdminTenant.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
