/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateLeaderboardsRequest: core.serialization.Schema<serializers.CreateLeaderboardsRequest.Raw, TrophyApi.CreateLeaderboardsRequest>;
export declare namespace CreateLeaderboardsRequest {
    type Raw = serializers.CreateLeaderboardRequestItem.Raw[];
}
