/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateLeaderboardsResponse: core.serialization.ObjectSchema<serializers.CreateLeaderboardsResponse.Raw, TrophyApi.CreateLeaderboardsResponse>;
export declare namespace CreateLeaderboardsResponse {
    interface Raw {
        created: serializers.AdminLeaderboard.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
