/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsTriggersRequestItemType: core.serialization.Schema<serializers.CreatePointsTriggersRequestItemType.Raw, TrophyApi.CreatePointsTriggersRequestItemType>;
export declare namespace CreatePointsTriggersRequestItemType {
    type Raw = "metric" | "achievement" | "streak" | "time" | "user_creation";
}
