/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsTriggerRequestItemStatus: core.serialization.Schema<serializers.CreatePointsTriggerRequestItemStatus.Raw, TrophyApi.CreatePointsTriggerRequestItemStatus>;
export declare namespace CreatePointsTriggerRequestItemStatus {
    type Raw = "active" | "inactive";
}
