/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsTriggersRequest: core.serialization.Schema<serializers.CreatePointsTriggersRequest.Raw, TrophyApi.CreatePointsTriggersRequest>;
export declare namespace CreatePointsTriggersRequest {
    type Raw = serializers.CreatePointsTriggersRequestItem.Raw[];
}
