/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateStreakFreezesResponse: core.serialization.ObjectSchema<serializers.CreateStreakFreezesResponse.Raw, TrophyApi.CreateStreakFreezesResponse>;
export declare namespace CreateStreakFreezesResponse {
    interface Raw {
        issues: serializers.BulkInsertIssue.Raw[];
    }
}
