/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsLevelsRequestItemBadge: core.serialization.ObjectSchema<serializers.CreatePointsLevelsRequestItemBadge.Raw, TrophyApi.CreatePointsLevelsRequestItemBadge>;
export declare namespace CreatePointsLevelsRequestItemBadge {
    interface Raw {
        url: string;
    }
}
