/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsSystemRequestItemBadge: core.serialization.ObjectSchema<serializers.CreatePointsSystemRequestItemBadge.Raw, TrophyApi.CreatePointsSystemRequestItemBadge>;
export declare namespace CreatePointsSystemRequestItemBadge {
    interface Raw {
        url: string;
    }
}
