/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsTriggersRequestItemEventAttributesItem: core.serialization.ObjectSchema<serializers.CreatePointsTriggersRequestItemEventAttributesItem.Raw, TrophyApi.CreatePointsTriggersRequestItemEventAttributesItem>;
export declare namespace CreatePointsTriggersRequestItemEventAttributesItem {
    interface Raw {
        attributeId: string;
        attributeValue: string;
    }
}
