/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateMetricsRequest: core.serialization.Schema<serializers.CreateMetricsRequest.Raw, TrophyApi.CreateMetricsRequest>;
export declare namespace CreateMetricsRequest {
    type Raw = serializers.CreateMetricRequestItem.Raw[];
}
