/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateAttributeRequestItem: core.serialization.ObjectSchema<serializers.CreateAttributeRequestItem.Raw, TrophyApi.CreateAttributeRequestItem>;
export declare namespace CreateAttributeRequestItem {
    interface Raw {
        name: string;
        key: string;
        type: serializers.CreateAttributeRequestItemType.Raw;
    }
}
