/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsBoostRequestItemRounding: core.serialization.Schema<serializers.CreatePointsBoostRequestItemRounding.Raw, TrophyApi.CreatePointsBoostRequestItemRounding>;
export declare namespace CreatePointsBoostRequestItemRounding {
    type Raw = "down" | "up" | "nearest";
}
