/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatedAdminPointsSystem: core.serialization.ObjectSchema<serializers.CreatedAdminPointsSystem.Raw, TrophyApi.CreatedAdminPointsSystem>;
export declare namespace CreatedAdminPointsSystem {
    interface Raw extends serializers.AdminPointsSystem.Raw {
        levels?: serializers.AdminPointsLevel.Raw[] | null;
        boosts?: serializers.AdminPointsBoost.Raw[] | null;
        triggers?: serializers.AdminPointsTrigger.Raw[] | null;
    }
}
