/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatedMetric: core.serialization.ObjectSchema<serializers.CreatedMetric.Raw, TrophyApi.CreatedMetric>;
export declare namespace CreatedMetric {
    interface Raw {
        id: string;
        name: string;
        key: string;
        unitType: serializers.CreatedMetricUnitType.Raw;
        units: string;
    }
}
