/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreatePointsBoostsRequestItemRounding: core.serialization.Schema<serializers.CreatePointsBoostsRequestItemRounding.Raw, TrophyApi.CreatePointsBoostsRequestItemRounding>;
export declare namespace CreatePointsBoostsRequestItemRounding {
    type Raw = "down" | "up" | "nearest";
}
