"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateAchievementRequestItem = void 0;
const core = __importStar(require("../../core"));
const CreateAchievementRequestItemBadge_1 = require("./CreateAchievementRequestItemBadge");
const CreateAchievementRequestItemEventAttributesItem_1 = require("./CreateAchievementRequestItemEventAttributesItem");
const CreateAchievementRequestItemStatus_1 = require("./CreateAchievementRequestItemStatus");
const CreateAchievementRequestItemTrigger_1 = require("./CreateAchievementRequestItemTrigger");
const CreateAchievementRequestItemUserAttributesItem_1 = require("./CreateAchievementRequestItemUserAttributesItem");
exports.CreateAchievementRequestItem = core.serialization.object({
    name: core.serialization.string(),
    trigger: CreateAchievementRequestItemTrigger_1.CreateAchievementRequestItemTrigger,
    description: core.serialization.string().optional(),
    status: CreateAchievementRequestItemStatus_1.CreateAchievementRequestItemStatus.optional(),
    badge: CreateAchievementRequestItemBadge_1.CreateAchievementRequestItemBadge.optional(),
    userAttributes: core.serialization.list(CreateAchievementRequestItemUserAttributesItem_1.CreateAchievementRequestItemUserAttributesItem).optional(),
    key: core.serialization.string().optional(),
    metricId: core.serialization.string().optional(),
    metricValue: core.serialization.number().optional(),
    eventAttributes: core.serialization.list(CreateAchievementRequestItemEventAttributesItem_1.CreateAchievementRequestItemEventAttributesItem).optional(),
    streakLength: core.serialization.number().optional(),
    anniversaryYears: core.serialization.number().optional(),
    achievementIds: core.serialization.list(core.serialization.string()).optional(),
});
