/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const CreateAttributeRequestItemType: core.serialization.Schema<serializers.CreateAttributeRequestItemType.Raw, TrophyApi.CreateAttributeRequestItemType>;
export declare namespace CreateAttributeRequestItemType {
    type Raw = "user" | "event";
}
