/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeleteMetricsResponse: core.serialization.ObjectSchema<serializers.DeleteMetricsResponse.Raw, TrophyApi.DeleteMetricsResponse>;
export declare namespace DeleteMetricsResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
