/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeleteLeaderboardsResponse: core.serialization.ObjectSchema<serializers.DeleteLeaderboardsResponse.Raw, TrophyApi.DeleteLeaderboardsResponse>;
export declare namespace DeleteLeaderboardsResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
