/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeletePointsLevelsResponse: core.serialization.ObjectSchema<serializers.DeletePointsLevelsResponse.Raw, TrophyApi.DeletePointsLevelsResponse>;
export declare namespace DeletePointsLevelsResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
