/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeleteAttributesResponse: core.serialization.ObjectSchema<serializers.DeleteAttributesResponse.Raw, TrophyApi.DeleteAttributesResponse>;
export declare namespace DeleteAttributesResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
