/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeleteTenantsResponse: core.serialization.ObjectSchema<serializers.DeleteTenantsResponse.Raw, TrophyApi.DeleteTenantsResponse>;
export declare namespace DeleteTenantsResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
