/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const DeletePointsTriggersResponse: core.serialization.ObjectSchema<serializers.DeletePointsTriggersResponse.Raw, TrophyApi.DeletePointsTriggersResponse>;
export declare namespace DeletePointsTriggersResponse {
    interface Raw {
        deleted: serializers.DeletedResource.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
