/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const EventRequestUser: core.serialization.ObjectSchema<serializers.EventRequestUser.Raw, TrophyApi.EventRequestUser>;
export declare namespace EventRequestUser {
    interface Raw {
        id: string;
        email?: string | null;
        name?: string | null;
        tz?: string | null;
    }
}
