/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const IncrementMetricStreakResponse: core.serialization.ObjectSchema<serializers.IncrementMetricStreakResponse.Raw, TrophyApi.IncrementMetricStreakResponse>;
export declare namespace IncrementMetricStreakResponse {
    interface Raw extends serializers.BaseStreakResponse.Raw {
        extended?: boolean | null;
    }
}
