/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const LeaderboardResponseRankBy: core.serialization.Schema<serializers.LeaderboardResponseRankBy.Raw, TrophyApi.LeaderboardResponseRankBy>;
export declare namespace LeaderboardResponseRankBy {
    type Raw = "points" | "streak" | "metric";
}
