/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const LeaderboardResponseStatus: core.serialization.Schema<serializers.LeaderboardResponseStatus.Raw, TrophyApi.LeaderboardResponseStatus>;
export declare namespace LeaderboardResponseStatus {
    type Raw = "active" | "scheduled" | "finished";
}
