/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const LeaderboardResponse: core.serialization.ObjectSchema<serializers.LeaderboardResponse.Raw, TrophyApi.LeaderboardResponse>;
export declare namespace LeaderboardResponse {
    interface Raw {
        id: string;
        name: string;
        key: string;
        status?: serializers.LeaderboardResponseStatus.Raw | null;
        rankBy: serializers.LeaderboardResponseRankBy.Raw;
        metricKey?: string | null;
        metricName?: string | null;
        pointsSystemKey?: string | null;
        pointsSystemName?: string | null;
        description?: string | null;
        start: string;
        end?: string | null;
        maxParticipants: number;
        runUnit?: string | null;
        runInterval: number;
    }
}
