/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const LeaderboardResponseBreakdownAttributesItem: core.serialization.ObjectSchema<serializers.LeaderboardResponseBreakdownAttributesItem.Raw, TrophyApi.LeaderboardResponseBreakdownAttributesItem>;
export declare namespace LeaderboardResponseBreakdownAttributesItem {
    interface Raw {
        key: string;
        name: string;
    }
}
