/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ListAttributesResponse: core.serialization.Schema<serializers.ListAttributesResponse.Raw, TrophyApi.ListAttributesResponse>;
export declare namespace ListAttributesResponse {
    type Raw = serializers.AdminAttribute.Raw[];
}
