/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ListTenantsResponse: core.serialization.Schema<serializers.ListTenantsResponse.Raw, TrophyApi.ListTenantsResponse>;
export declare namespace ListTenantsResponse {
    type Raw = serializers.AdminTenant.Raw[];
}
