/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ListPointsBoostsResponse: core.serialization.Schema<serializers.ListPointsBoostsResponse.Raw, TrophyApi.ListPointsBoostsResponse>;
export declare namespace ListPointsBoostsResponse {
    type Raw = serializers.AdminPointsBoost.Raw[];
}
