/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ListMetricsResponse: core.serialization.Schema<serializers.ListMetricsResponse.Raw, TrophyApi.ListMetricsResponse>;
export declare namespace ListMetricsResponse {
    type Raw = serializers.CreatedMetric.Raw[];
}
