/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const ListPointsSystemsResponse: core.serialization.Schema<serializers.ListPointsSystemsResponse.Raw, TrophyApi.ListPointsSystemsResponse>;
export declare namespace ListPointsSystemsResponse {
    type Raw = serializers.AdminPointsSystem.Raw[];
}
