/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const MetricEventPointsResponse: core.serialization.ObjectSchema<serializers.MetricEventPointsResponse.Raw, TrophyApi.MetricEventPointsResponse>;
export declare namespace MetricEventPointsResponse {
    interface Raw {
        id: string;
        key: string;
        name: string;
        description?: string | null;
        badgeUrl?: string | null;
        maxPoints?: number | null;
        total: number;
        level?: serializers.PointsLevel.Raw | null;
        added: number;
        awards: serializers.PointsAward.Raw[];
    }
}
