/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const MetricEventLeaderboardResponse: core.serialization.ObjectSchema<serializers.MetricEventLeaderboardResponse.Raw, TrophyApi.MetricEventLeaderboardResponse>;
export declare namespace MetricEventLeaderboardResponse {
    interface Raw {
        end?: string | null;
        rank?: number | null;
        previousRank?: number | null;
        threshold: number;
        breakdownAttributeValue?: string | null;
        id: string;
        name: string;
        key: string;
        rankBy: serializers.LeaderboardResponseRankBy.Raw;
        breakdownAttribute?: string | null;
        metricKey?: string | null;
        metricName?: string | null;
        pointsSystemKey?: string | null;
        pointsSystemName?: string | null;
        description?: string | null;
        start: string;
        maxParticipants: number;
        runUnit?: serializers.LeaderboardResponseRunUnit.Raw | null;
        runInterval?: number | null;
    }
}
