/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const MetricAchievementResponse: core.serialization.ObjectSchema<serializers.MetricAchievementResponse.Raw, TrophyApi.MetricAchievementResponse>;
export declare namespace MetricAchievementResponse {
    interface Raw extends serializers.BaseAchievementResponse.Raw {
        trigger: string;
        metricId: string;
        metricValue: number;
        metricName: string;
    }
}
