/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const OneOffAchievementResponse: core.serialization.ObjectSchema<serializers.OneOffAchievementResponse.Raw, TrophyApi.OneOffAchievementResponse>;
export declare namespace OneOffAchievementResponse {
    interface Raw {
        id: string;
        name?: string | null;
        badgeUrl?: string | null;
        key?: string | null;
        achievedAt?: string | null;
    }
}
