/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsLevelsRequest: core.serialization.Schema<serializers.PatchPointsLevelsRequest.Raw, TrophyApi.PatchPointsLevelsRequest>;
export declare namespace PatchPointsLevelsRequest {
    type Raw = serializers.PatchPointsLevelsRequestItem.Raw[];
}
