/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsLevelsResponse: core.serialization.ObjectSchema<serializers.PatchPointsLevelsResponse.Raw, TrophyApi.PatchPointsLevelsResponse>;
export declare namespace PatchPointsLevelsResponse {
    interface Raw {
        updated: serializers.AdminPointsLevel.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
