/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsTriggersRequestItemTimeUnit: core.serialization.Schema<serializers.PatchPointsTriggersRequestItemTimeUnit.Raw, TrophyApi.PatchPointsTriggersRequestItemTimeUnit>;
export declare namespace PatchPointsTriggersRequestItemTimeUnit {
    type Raw = "hours" | "days";
}
