/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchMetricsResponse: core.serialization.ObjectSchema<serializers.PatchMetricsResponse.Raw, TrophyApi.PatchMetricsResponse>;
export declare namespace PatchMetricsResponse {
    interface Raw {
        updated: serializers.CreatedMetric.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
