/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsTriggersRequestItem: core.serialization.ObjectSchema<serializers.PatchPointsTriggersRequestItem.Raw, TrophyApi.PatchPointsTriggersRequestItem>;
export declare namespace PatchPointsTriggersRequestItem {
    interface Raw {
        id: string;
        type?: serializers.PatchPointsTriggersRequestItemType.Raw | null;
        points?: number | null;
        status?: serializers.PatchPointsTriggersRequestItemStatus.Raw | null;
        userAttributes?: serializers.PatchPointsTriggersRequestItemUserAttributesItem.Raw[] | null;
        metricId?: string | null;
        metricThreshold?: number | null;
        eventAttributes?: serializers.PatchPointsTriggersRequestItemEventAttributesItem.Raw[] | null;
        achievementId?: string | null;
        streakLength?: number | null;
        timeUnit?: serializers.PatchPointsTriggersRequestItemTimeUnit.Raw | null;
        timeInterval?: number | null;
        blockIfOutOfPoints?: boolean | null;
    }
}
