/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsTriggersRequestItemStatus: core.serialization.Schema<serializers.PatchPointsTriggersRequestItemStatus.Raw, TrophyApi.PatchPointsTriggersRequestItemStatus>;
export declare namespace PatchPointsTriggersRequestItemStatus {
    type Raw = "active" | "inactive";
}
