/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsBoostsRequest: core.serialization.Schema<serializers.PatchPointsBoostsRequest.Raw, TrophyApi.PatchPointsBoostsRequest>;
export declare namespace PatchPointsBoostsRequest {
    type Raw = serializers.PatchPointsBoostsRequestItem.Raw[];
}
