/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsTriggersRequest: core.serialization.Schema<serializers.PatchPointsTriggersRequest.Raw, TrophyApi.PatchPointsTriggersRequest>;
export declare namespace PatchPointsTriggersRequest {
    type Raw = serializers.PatchPointsTriggersRequestItem.Raw[];
}
