/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchMetricsRequest: core.serialization.Schema<serializers.PatchMetricsRequest.Raw, TrophyApi.PatchMetricsRequest>;
export declare namespace PatchMetricsRequest {
    type Raw = serializers.PatchMetricRequestItem.Raw[];
}
