/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PatchPointsTriggersRequestItemEventAttributesItem: core.serialization.ObjectSchema<serializers.PatchPointsTriggersRequestItemEventAttributesItem.Raw, TrophyApi.PatchPointsTriggersRequestItemEventAttributesItem>;
export declare namespace PatchPointsTriggersRequestItemEventAttributesItem {
    interface Raw {
        attributeId: string;
        attributeValue: string;
    }
}
