/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerEventAttributesItem: core.serialization.ObjectSchema<serializers.PointsTriggerEventAttributesItem.Raw, TrophyApi.PointsTriggerEventAttributesItem>;
export declare namespace PointsTriggerEventAttributesItem {
    interface Raw {
        key: string;
        value: string;
    }
}
