/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsSystemResponse: core.serialization.ObjectSchema<serializers.PointsSystemResponse.Raw, TrophyApi.PointsSystemResponse>;
export declare namespace PointsSystemResponse {
    interface Raw {
        id: string;
        name: string;
        description?: string | null;
        badgeUrl?: string | null;
        maxPoints?: number | null;
        triggers: serializers.PointsTriggerResponse.Raw[];
    }
}
