/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerStatus: core.serialization.Schema<serializers.PointsTriggerStatus.Raw, TrophyApi.PointsTriggerStatus>;
export declare namespace PointsTriggerStatus {
    type Raw = "active" | "inactive" | "archived";
}
