/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsSummaryResponse: core.serialization.Schema<serializers.PointsSummaryResponse.Raw, TrophyApi.PointsSummaryResponse>;
export declare namespace PointsSummaryResponse {
    type Raw = serializers.PointsRange.Raw[];
}
