/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsAward: core.serialization.ObjectSchema<serializers.PointsAward.Raw, TrophyApi.PointsAward>;
export declare namespace PointsAward {
    interface Raw {
        id?: string | null;
        awarded?: number | null;
        trigger?: serializers.PointsTrigger.Raw | null;
    }
}
