/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerResponse: core.serialization.ObjectSchema<serializers.PointsTriggerResponse.Raw, TrophyApi.PointsTriggerResponse>;
export declare namespace PointsTriggerResponse {
    interface Raw {
        id?: string | null;
        type?: serializers.PointsTriggerResponseType.Raw | null;
        points?: number | null;
        status?: serializers.PointsTriggerResponseStatus.Raw | null;
        achievementId?: string | null;
        metricId?: string | null;
        metricThreshold?: number | null;
        streakLengthThreshold?: number | null;
        metricName?: string | null;
        achievementName?: string | null;
        userAttributes?: serializers.PointsTriggerResponseUserAttributesItem.Raw[] | null;
        eventAttribute?: serializers.PointsTriggerResponseEventAttribute.Raw | null;
        created?: string | null;
        updated?: string | null;
    }
}
