/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerResponseEventAttribute: core.serialization.ObjectSchema<serializers.PointsTriggerResponseEventAttribute.Raw, TrophyApi.PointsTriggerResponseEventAttribute>;
export declare namespace PointsTriggerResponseEventAttribute {
    interface Raw {
        key: string;
        value: string;
    }
}
