/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerResponseUserAttributesItem: core.serialization.ObjectSchema<serializers.PointsTriggerResponseUserAttributesItem.Raw, TrophyApi.PointsTriggerResponseUserAttributesItem>;
export declare namespace PointsTriggerResponseUserAttributesItem {
    interface Raw {
        key: string;
        value: string;
    }
}
