/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsBoostStatus: core.serialization.Schema<serializers.PointsBoostStatus.Raw, TrophyApi.PointsBoostStatus>;
export declare namespace PointsBoostStatus {
    type Raw = "active" | "scheduled" | "finished";
}
