/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsBoostWebhookPayloadRounding: core.serialization.Schema<serializers.PointsBoostWebhookPayloadRounding.Raw, TrophyApi.PointsBoostWebhookPayloadRounding>;
export declare namespace PointsBoostWebhookPayloadRounding {
    type Raw = "down" | "up" | "nearest";
}
