/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsBoostWebhookPayloadStatus: core.serialization.Schema<serializers.PointsBoostWebhookPayloadStatus.Raw, TrophyApi.PointsBoostWebhookPayloadStatus>;
export declare namespace PointsBoostWebhookPayloadStatus {
    type Raw = "active" | "finished";
}
