/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsBoost: core.serialization.ObjectSchema<serializers.PointsBoost.Raw, TrophyApi.PointsBoost>;
export declare namespace PointsBoost {
    interface Raw {
        id?: string | null;
        name?: string | null;
        start?: string | null;
        end?: string | null;
        multiplier?: number | null;
        rounding?: serializers.PointsBoostRounding.Raw | null;
    }
}
