/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsTriggerResponseTimeUnit: core.serialization.Schema<serializers.PointsTriggerResponseTimeUnit.Raw, TrophyApi.PointsTriggerResponseTimeUnit>;
export declare namespace PointsTriggerResponseTimeUnit {
    type Raw = "hour" | "day";
}
