/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsResponse: core.serialization.ObjectSchema<serializers.PointsResponse.Raw, TrophyApi.PointsResponse>;
export declare namespace PointsResponse {
    interface Raw {
        id: string;
        key: string;
        name: string;
        description?: string | null;
        badgeUrl?: string | null;
        maxPoints?: number | null;
    }
}
