/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const PointsBoostWebhookPayload: core.serialization.ObjectSchema<serializers.PointsBoostWebhookPayload.Raw, TrophyApi.PointsBoostWebhookPayload>;
export declare namespace PointsBoostWebhookPayload {
    interface Raw {
        id: string;
        name: string;
        status: serializers.PointsBoostWebhookPayloadStatus.Raw;
        pointsSystemId: string;
        pointsSystemKey: string;
        pointsSystemName: string;
        start: string;
        end?: string | null;
        multiplier: number;
        rounding: serializers.PointsBoostWebhookPayloadRounding.Raw;
    }
}
