/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const RestoreStreaksResponse: core.serialization.ObjectSchema<serializers.RestoreStreaksResponse.Raw, TrophyApi.RestoreStreaksResponse>;
export declare namespace RestoreStreaksResponse {
    interface Raw {
        restoredUsers: string[];
        issues: serializers.BulkInsertIssue.Raw[];
    }
}
