/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const StreakResponseStreakHistoryItem: core.serialization.ObjectSchema<serializers.StreakResponseStreakHistoryItem.Raw, TrophyApi.StreakResponseStreakHistoryItem>;
export declare namespace StreakResponseStreakHistoryItem {
    interface Raw {
        periodStart: string;
        periodEnd: string;
        length: number;
        usedFreeze?: boolean | null;
    }
}
