/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdatePointsSystemsRequest: core.serialization.Schema<serializers.UpdatePointsSystemsRequest.Raw, TrophyApi.UpdatePointsSystemsRequest>;
export declare namespace UpdatePointsSystemsRequest {
    type Raw = serializers.UpdatePointsSystemRequestItem.Raw[];
}
