/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateLeaderboardRequestItemRankBy: core.serialization.Schema<serializers.UpdateLeaderboardRequestItemRankBy.Raw, TrophyApi.UpdateLeaderboardRequestItemRankBy>;
export declare namespace UpdateLeaderboardRequestItemRankBy {
    type Raw = "metric" | "streak" | "points";
}
