/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateLeaderboardsResponse: core.serialization.ObjectSchema<serializers.UpdateLeaderboardsResponse.Raw, TrophyApi.UpdateLeaderboardsResponse>;
export declare namespace UpdateLeaderboardsResponse {
    interface Raw {
        updated: serializers.AdminLeaderboard.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
