/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdatePointsSystemsResponse: core.serialization.ObjectSchema<serializers.UpdatePointsSystemsResponse.Raw, TrophyApi.UpdatePointsSystemsResponse>;
export declare namespace UpdatePointsSystemsResponse {
    interface Raw {
        updated: serializers.AdminPointsSystem.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
