/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateAttributeRequestItem: core.serialization.ObjectSchema<serializers.UpdateAttributeRequestItem.Raw, TrophyApi.UpdateAttributeRequestItem>;
export declare namespace UpdateAttributeRequestItem {
    interface Raw {
        id: string;
        name?: string | null;
    }
}
