/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateAttributesResponse: core.serialization.ObjectSchema<serializers.UpdateAttributesResponse.Raw, TrophyApi.UpdateAttributesResponse>;
export declare namespace UpdateAttributesResponse {
    interface Raw {
        updated: serializers.AdminAttribute.Raw[];
        issues: serializers.AdminIssue.Raw[];
    }
}
