/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdatePointsSystemRequestItemBadge: core.serialization.ObjectSchema<serializers.UpdatePointsSystemRequestItemBadge.Raw, TrophyApi.UpdatePointsSystemRequestItemBadge>;
export declare namespace UpdatePointsSystemRequestItemBadge {
    interface Raw {
        url: string;
    }
}
