/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateTenantsRequest: core.serialization.Schema<serializers.UpdateTenantsRequest.Raw, TrophyApi.UpdateTenantsRequest>;
export declare namespace UpdateTenantsRequest {
    type Raw = serializers.UpdateTenantRequestItem.Raw[];
}
