/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateMetricsRequest: core.serialization.Schema<serializers.UpdateMetricsRequest.Raw, TrophyApi.UpdateMetricsRequest>;
export declare namespace UpdateMetricsRequest {
    type Raw = serializers.UpdateMetricRequestItem.Raw[];
}
