/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateMetricRequestItem: core.serialization.ObjectSchema<serializers.UpdateMetricRequestItem.Raw, TrophyApi.UpdateMetricRequestItem>;
export declare namespace UpdateMetricRequestItem {
    interface Raw {
        id: string;
        name?: string | null;
        unitType?: serializers.UpdateMetricRequestItemUnitType.Raw | null;
        units?: string | null;
    }
}
