/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateLeaderboardRequestItem: core.serialization.ObjectSchema<serializers.UpdateLeaderboardRequestItem.Raw, TrophyApi.UpdateLeaderboardRequestItem>;
export declare namespace UpdateLeaderboardRequestItem {
    interface Raw {
        id: string;
        name?: string | null;
        key?: string | null;
        description?: string | null;
        status?: serializers.UpdateLeaderboardRequestItemStatus.Raw | null;
        rankBy?: serializers.UpdateLeaderboardRequestItemRankBy.Raw | null;
        metricId?: string | null;
        pointsSystemId?: string | null;
        maxParticipants?: number | null;
        start?: string | null;
        end?: string | null;
        breakdownAttributes?: string[] | null;
        runUnit?: serializers.UpdateLeaderboardRequestItemRunUnit.Raw | null;
        runInterval?: number | null;
    }
}
