/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateLeaderboardRequestItemRunUnit: core.serialization.Schema<serializers.UpdateLeaderboardRequestItemRunUnit.Raw, TrophyApi.UpdateLeaderboardRequestItemRunUnit>;
export declare namespace UpdateLeaderboardRequestItemRunUnit {
    type Raw = "day" | "month" | "year";
}
