/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateLeaderboardsRequest: core.serialization.Schema<serializers.UpdateLeaderboardsRequest.Raw, TrophyApi.UpdateLeaderboardsRequest>;
export declare namespace UpdateLeaderboardsRequest {
    type Raw = serializers.UpdateLeaderboardRequestItem.Raw[];
}
