/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdatedUser: core.serialization.ObjectSchema<serializers.UpdatedUser.Raw, TrophyApi.UpdatedUser>;
export declare namespace UpdatedUser {
    interface Raw {
        email: string;
        name: string;
        tz?: string | null;
        deviceTokens: string[];
        subscribeToEmails: boolean;
        attributes: Record<string, string>;
    }
}
