/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateMetricRequestItemUnitType: core.serialization.Schema<serializers.UpdateMetricRequestItemUnitType.Raw, TrophyApi.UpdateMetricRequestItemUnitType>;
export declare namespace UpdateMetricRequestItemUnitType {
    type Raw = "number" | "currency";
}
