/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdatePointsSystemRequestItem: core.serialization.ObjectSchema<serializers.UpdatePointsSystemRequestItem.Raw, TrophyApi.UpdatePointsSystemRequestItem>;
export declare namespace UpdatePointsSystemRequestItem {
    interface Raw {
        id: string;
        name?: string | null;
        description?: string | null;
        badge?: serializers.UpdatePointsSystemRequestItemBadge.Raw | null;
        maxPoints?: number | null;
    }
}
