/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UpdateAttributesRequest: core.serialization.Schema<serializers.UpdateAttributesRequest.Raw, TrophyApi.UpdateAttributesRequest>;
export declare namespace UpdateAttributesRequest {
    type Raw = serializers.UpdateAttributeRequestItem.Raw[];
}
