/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UserPreferencesResponse: core.serialization.ObjectSchema<serializers.UserPreferencesResponse.Raw, TrophyApi.UserPreferencesResponse>;
export declare namespace UserPreferencesResponse {
    interface Raw {
        notifications: serializers.NotificationPreferences.Raw;
    }
}
