/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UserLeaderboardResponse: core.serialization.ObjectSchema<serializers.UserLeaderboardResponse.Raw, TrophyApi.UserLeaderboardResponse>;
export declare namespace UserLeaderboardResponse {
    interface Raw extends serializers.LeaderboardResponse.Raw {
        rank?: number | null;
        value?: number | null;
    }
}
