/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const User: core.serialization.ObjectSchema<serializers.User.Raw, TrophyApi.User>;
export declare namespace User {
    interface Raw {
        id: string;
        email?: string | null;
        name?: string | null;
        tz?: string | null;
        deviceTokens?: string[] | null;
        subscribeToEmails: boolean;
        attributes: Record<string, string>;
        control: boolean;
        created: string;
        updated: string;
    }
}
