/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UserLeaderboardResponseWithHistory: core.serialization.ObjectSchema<serializers.UserLeaderboardResponseWithHistory.Raw, TrophyApi.UserLeaderboardResponseWithHistory>;
export declare namespace UserLeaderboardResponseWithHistory {
    interface Raw extends serializers.UserLeaderboardResponse.Raw {
        history: serializers.LeaderboardEvent.Raw[];
    }
}
