/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const UserAchievementWithStatsResponse: core.serialization.ObjectSchema<serializers.UserAchievementWithStatsResponse.Raw, TrophyApi.UserAchievementWithStatsResponse>;
export declare namespace UserAchievementWithStatsResponse {
    interface Raw extends serializers.AchievementWithStatsResponse.Raw {
        achievedAt?: string | null;
    }
}
