/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const User: core.serialization.ObjectSchema<serializers.User.Raw, TrophyApi.User>;
export declare namespace User {
    interface Raw extends serializers.UpsertedUser.Raw {
        control: boolean;
        created: string;
        updated: string;
    }
}
