/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksPointsBoostFinishedPayload: core.serialization.ObjectSchema<serializers.WebhooksPointsBoostFinishedPayload.Raw, TrophyApi.WebhooksPointsBoostFinishedPayload>;
export declare namespace WebhooksPointsBoostFinishedPayload {
    interface Raw {
        type: "points.boost_finished";
        timestamp: string;
        boost: serializers.PointsBoostWebhookPayload.Raw;
    }
}
