/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksStreakExtendedPayload: core.serialization.ObjectSchema<serializers.WebhooksStreakExtendedPayload.Raw, TrophyApi.WebhooksStreakExtendedPayload>;
export declare namespace WebhooksStreakExtendedPayload {
    interface Raw {
        type: "streak.extended";
        user: serializers.User.Raw;
        streak: serializers.BaseStreakResponse.Raw;
    }
}
