/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksPointsLevelChangedPayload: core.serialization.ObjectSchema<serializers.WebhooksPointsLevelChangedPayload.Raw, TrophyApi.WebhooksPointsLevelChangedPayload>;
export declare namespace WebhooksPointsLevelChangedPayload {
    interface Raw {
        type: "points.level_changed";
        user: serializers.User.Raw;
        points: serializers.WebhooksPointsLevelChangedPayloadPoints.Raw;
        previousLevel?: serializers.PointsLevel.Raw | null;
        newLevel?: serializers.PointsLevel.Raw | null;
    }
}
