/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksLeaderboardStartedPayload: core.serialization.ObjectSchema<serializers.WebhooksLeaderboardStartedPayload.Raw, TrophyApi.WebhooksLeaderboardStartedPayload>;
export declare namespace WebhooksLeaderboardStartedPayload {
    interface Raw {
        type: "leaderboard.started";
        leaderboard: serializers.LeaderboardResponseWithRankings.Raw;
    }
}
