/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksAchievementCompletedPayload: core.serialization.ObjectSchema<serializers.WebhooksAchievementCompletedPayload.Raw, TrophyApi.WebhooksAchievementCompletedPayload>;
export declare namespace WebhooksAchievementCompletedPayload {
    interface Raw {
        type: "achievement.completed";
        user: serializers.User.Raw;
        achievement: serializers.CompletedAchievementResponse.Raw;
    }
}
