/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksStreakLostPayload: core.serialization.ObjectSchema<serializers.WebhooksStreakLostPayload.Raw, TrophyApi.WebhooksStreakLostPayload>;
export declare namespace WebhooksStreakLostPayload {
    interface Raw {
        type: "streak.lost";
        user: serializers.User.Raw;
        length: number;
    }
}
