/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksStreakFreezeConsumedPayload: core.serialization.ObjectSchema<serializers.WebhooksStreakFreezeConsumedPayload.Raw, TrophyApi.WebhooksStreakFreezeConsumedPayload>;
export declare namespace WebhooksStreakFreezeConsumedPayload {
    interface Raw {
        type: "streak.freeze_consumed";
        user: serializers.User.Raw;
        consumed: number;
        freezes: number;
    }
}
