/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksPointsLevelChangedPayloadPoints: core.serialization.ObjectSchema<serializers.WebhooksPointsLevelChangedPayloadPoints.Raw, TrophyApi.WebhooksPointsLevelChangedPayloadPoints>;
export declare namespace WebhooksPointsLevelChangedPayloadPoints {
    interface Raw extends serializers.PointsResponse.Raw {
        total: number;
    }
}
