/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WebhooksPointsChangedPayload: core.serialization.ObjectSchema<serializers.WebhooksPointsChangedPayload.Raw, TrophyApi.WebhooksPointsChangedPayload>;
export declare namespace WebhooksPointsChangedPayload {
    interface Raw {
        type: "points.changed";
        user: serializers.User.Raw;
        points: serializers.GetUserPointsResponse.Raw;
    }
}
