/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WrappedMostActiveDay: core.serialization.ObjectSchema<serializers.WrappedMostActiveDay.Raw, TrophyApi.WrappedMostActiveDay>;
export declare namespace WrappedMostActiveDay {
    interface Raw extends serializers.WrappedActivityPeriod.Raw {
        date: string;
    }
}
