/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WrappedMetric: core.serialization.ObjectSchema<serializers.WrappedMetric.Raw, TrophyApi.WrappedMetric>;
export declare namespace WrappedMetric {
    interface Raw {
        name: string;
        units?: string | null;
        currentTotal: number;
        changeThisPeriod: number;
        percentChange: number;
        percentileThisPeriod?: number | null;
        byAttribute: Record<string, Record<string, serializers.WrappedMetricByAttributeValueValue.Raw>>;
    }
}
