/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as TrophyApi from "../../api";
import * as core from "../../core";
export declare const WrappedResponse: core.serialization.ObjectSchema<serializers.WrappedResponse.Raw, TrophyApi.WrappedResponse>;
export declare namespace WrappedResponse {
    interface Raw {
        user: serializers.User.Raw;
        activity: serializers.WrappedActivity.Raw;
    }
}
