/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export declare type AchievementResponse = TrophyApi.MetricAchievementResponse | TrophyApi.StreakAchievementResponse | TrophyApi.ApiAchievementResponse;
