"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AchievementResponseTrigger = void 0;
/** The trigger of the achievement. */
exports.AchievementResponseTrigger = {
    Metric: "metric",
    Streak: "streak",
    Api: "api",
    Achievement: "achievement",
};
