/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The trigger of the achievement.
 */
export declare type AchievementResponseTrigger = "metric" | "streak" | "api";
export declare const AchievementResponseTrigger: {
    readonly Metric: "metric";
    readonly Streak: "streak";
    readonly Api: "api";
};
