/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The time unit, or null if not a time trigger.
 */
export declare type AdminPointsTriggerTimeUnit = "hours" | "days";
export declare const AdminPointsTriggerTimeUnit: {
    readonly Hours: "hours";
    readonly Days: "days";
};
