"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminLeaderboardStatus = void 0;
/** The current user-facing status of the leaderboard. */
exports.AdminLeaderboardStatus = {
    Inactive: "inactive",
    Active: "active",
    Scheduled: "scheduled",
    Finished: "finished",
};
