"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminStreakEvaluationMode = void 0;
/** Whether meeting any single metric threshold (`OR`) or all configured metric thresholds (`AND`) extends the user's streak. */
exports.AdminStreakEvaluationMode = {
    Or: "OR",
    And: "AND",
};
