/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The lifecycle status of the tenant.
 */
export declare type AdminTenantStatus = "active" | "archived";
export declare const AdminTenantStatus: {
    readonly Active: "active";
    readonly Archived: "archived";
};
