"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminStreakPauseStatus = void 0;
/** The status of the pause. */
exports.AdminStreakPauseStatus = {
    Active: "active",
    Archived: "archived",
};
