/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The points system status.
 */
export declare type AdminPointsSystemStatus = "active" | "archived";
export declare const AdminPointsSystemStatus: {
    readonly Active: "active";
    readonly Archived: "archived";
};
