"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminIssueSeverity = void 0;
/** The severity level of the issue. */
exports.AdminIssueSeverity = {
    Error: "error",
    Warning: "warning",
};
