"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminPointsTriggerStatus = void 0;
/** The status of the trigger. */
exports.AdminPointsTriggerStatus = {
    Active: "active",
    Inactive: "inactive",
};
