"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminAchievementStatus = void 0;
/** The achievement status. */
exports.AdminAchievementStatus = {
    Active: "active",
    Inactive: "inactive",
    Locked: "locked",
};
