/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A points level as returned from admin endpoints.
 */
export interface AdminPointsLevel {
    /** The UUID of the level. */
    id: string;
    /** The name of the level. */
    name: string;
    /** The level key. */
    key: string;
    /** The threshold points value for the level. */
    points: number;
    /** The level description. */
    description: string;
    /** The badge for the level, or null if no badge is set. */
    badge?: TrophyApi.AdminPointsLevelBadge;
}
