"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminLeaderboardRunUnit = void 0;
exports.AdminLeaderboardRunUnit = {
    Day: "day",
    Month: "month",
    Year: "year",
};
