"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminAggregationPeriod = void 0;
/** How progress is displayed in email chart blocks and how often recap messages send. */
exports.AdminAggregationPeriod = {
    Weekly: "weekly",
    Monthly: "monthly",
};
