/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The recurrence unit when the leaderboard repeats.
 */
export declare type AdminLeaderboardRunUnit = "day" | "month" | "year";
export declare const AdminLeaderboardRunUnit: {
    readonly Day: "day";
    readonly Month: "month";
    readonly Year: "year";
};
