/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * What the leaderboard ranks by.
 */
export declare type AdminLeaderboardRankBy = "metric" | "streak" | "points";
export declare const AdminLeaderboardRankBy: {
    readonly Metric: "metric";
    readonly Streak: "streak";
    readonly Points: "points";
};
