"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminStreakFrequency = void 0;
/** The frequency at which streaks are calculated. */
exports.AdminStreakFrequency = {
    Daily: "daily",
    Weekly: "weekly",
    Monthly: "monthly",
};
