/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * An attribute returned from the admin attributes endpoints.
 */
export interface AdminAttribute {
    /** The UUID of the attribute. */
    id: string;
    /** The attribute name. */
    name: string;
    /** The attribute key. */
    key: string;
    /** The attribute type. */
    type: TrophyApi.AdminAttributeType;
}
