/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The current user-facing status of the leaderboard.
 */
export declare type AdminLeaderboardStatus = "inactive" | "active" | "scheduled" | "finished";
export declare const AdminLeaderboardStatus: {
    readonly Inactive: "inactive";
    readonly Active: "active";
    readonly Scheduled: "scheduled";
    readonly Finished: "finished";
};
