/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * How boosted points are rounded.
 */
export declare type AdminPointsBoostRounding = "down" | "up" | "nearest";
export declare const AdminPointsBoostRounding: {
    readonly Down: "down";
    readonly Up: "up";
    readonly Nearest: "nearest";
};
