"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminPointsBoostStatus = void 0;
/** The status of the boost. */
exports.AdminPointsBoostStatus = {
    Active: "active",
    Scheduled: "scheduled",
    Finished: "finished",
};
