/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A points boost as returned from admin endpoints.
 */
export interface AdminPointsBoost {
    /** The UUID of the boost. */
    id: string;
    /** The name of the boost. */
    name: string;
    /** The status of the boost. */
    status: TrophyApi.AdminPointsBoostStatus;
    /** The start date (YYYY-MM-DD). */
    start: string;
    /** The end date (YYYY-MM-DD) or null if no end date. */
    end?: string;
    /** The points multiplier. */
    multiplier: number;
    /** How boosted points are rounded. */
    rounding: TrophyApi.AdminPointsBoostRounding;
    /** The customer ID of the user the boost was created for, or null for global/attribute-filtered boosts. */
    userId?: string;
    /** User attribute filters applied to the boost. Only present for non-user-specific boosts (i.e. when `userId` is null). Empty array if no filters are set. */
    userAttributes?: TrophyApi.AdminPointsBoostUserAttributesItem[];
}
