/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface CompletedAchievementResponse extends TrophyApi.AchievementResponse {
    /** The date and time the achievement was completed, in ISO 8601 format. */
    achievedAt: Date;
}
