/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Request body for creating tenants.
 */
export declare type CreateTenantsRequest = TrophyApi.CreateTenantRequestItem[];
