"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateLeaderboardRequestItemRunUnit = void 0;
/** How often the leaderboard repeats. Omit for a non-recurring leaderboard. Streak leaderboards cannot repeat. */
exports.CreateLeaderboardRequestItemRunUnit = {
    Day: "day",
    Month: "month",
    Year: "year",
};
