/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The initial user-facing status. Defaults to `inactive`. Use `scheduled` for leaderboards that should be active in the future and `finished` only when creating a leaderboard with an end date in the past.
 */
export declare type CreateLeaderboardRequestItemStatus = "inactive" | "active" | "scheduled" | "finished";
export declare const CreateLeaderboardRequestItemStatus: {
    readonly Inactive: "inactive";
    readonly Active: "active";
    readonly Scheduled: "scheduled";
    readonly Finished: "finished";
};
