/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface CreatePointsTriggersRequestItemEventAttributesItem {
    /** The UUID of the event attribute. */
    attributeId: string;
    /** The value to match. */
    attributeValue: string;
}
