/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Array of points levels to create. Maximum 100 levels per request.
 */
export declare type CreatePointsLevelsRequest = TrophyApi.CreatePointsLevelsRequestItem[];
