/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing created levels and any per-item issues.
 */
export interface CreatePointsLevelsResponse {
    /** Array of successfully created levels. */
    created: TrophyApi.AdminPointsLevel[];
    /** Array of issues encountered during level creation. */
    issues: TrophyApi.AdminIssue[];
}
