/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing created attributes and any per-item issues.
 */
export interface CreateAttributesResponse {
    /** Array of successfully created attributes. */
    created: TrophyApi.AdminAttribute[];
    /** Array of issues encountered during attribute creation. */
    issues: TrophyApi.AdminIssue[];
}
