/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The initial status. `active` behaves the same as activating or scheduling the leaderboard in the dashboard.
 */
export declare type CreateLeaderboardRequestItemStatus = "active" | "inactive";
export declare const CreateLeaderboardRequestItemStatus: {
    readonly Active: "active";
    readonly Inactive: "inactive";
};
