/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The metric unit type. Defaults to `number`.
 */
export declare type CreateMetricRequestItemUnitType = "number" | "currency";
export declare const CreateMetricRequestItemUnitType: {
    readonly Number: "number";
    readonly Currency: "currency";
};
