/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A points system returned from the creation endpoint. Extends AdminPointsSystem with optional sub-entity arrays that are present when those sub-entities were included in the creation request.
 */
export interface CreatedAdminPointsSystem extends TrophyApi.AdminPointsSystem {
    /** Levels created alongside the system. Present when levels were provided in the request. */
    levels?: TrophyApi.AdminPointsLevel[];
    /** Boosts created alongside the system. Present when boosts were provided in the request. */
    boosts?: TrophyApi.AdminPointsBoost[];
    /** Triggers created alongside the system. Present when triggers were provided in the request. */
    triggers?: TrophyApi.AdminPointsTrigger[];
}
