/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An optional badge for the level.
 */
export interface CreatePointsLevelRequestItemBadge {
    /** The URL of the badge image. */
    url: string;
}
