"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateAchievementRequestItemStatus = void 0;
/** The achievement status. Defaults to `inactive`. */
exports.CreateAchievementRequestItemStatus = {
    Active: "active",
    Inactive: "inactive",
    Locked: "locked",
};
