/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A successfully created metric returned from the create endpoint.
 */
export interface CreatedMetric {
    /** The UUID of the created metric. */
    id: string;
    /** The metric name. */
    name: string;
    /** The metric key. */
    key: string;
    /** The metric unit type. */
    unitType: TrophyApi.CreatedMetricUnitType;
    /** The stored units value for the metric. */
    units: string;
}
