/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Request body for creating points systems.
 */
export declare type CreatePointsSystemsRequest = TrophyApi.CreatePointsSystemRequestItem[];
