/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing created boosts and any issues encountered while creating points boosts.
 */
export interface CreatePointsBoostsResponse {
    /** Array of successfully created boosts. */
    created: TrophyApi.CreatedPointsBoost[];
    /** Array of issues encountered during boost creation. */
    issues: TrophyApi.AdminIssue[];
}
