"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreatePointsBoostRequestItemRounding = void 0;
exports.CreatePointsBoostRequestItemRounding = {
    Down: "down",
    Up: "up",
    Nearest: "nearest",
};
