/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing any issues encountered while creating streak freezes.
 */
export interface CreateStreakFreezesResponse {
    /** Array of issues encountered during freeze creation. */
    issues: TrophyApi.BulkInsertIssue[];
}
