/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The attribute type.
 */
export declare type CreateAttributeRequestItemType = "user" | "event";
export declare const CreateAttributeRequestItemType: {
    readonly User: "user";
    readonly Event: "event";
};
