"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateLeaderboardRequestItemRankBy = void 0;
/** What the leaderboard ranks by. */
exports.CreateLeaderboardRequestItemRankBy = {
    Metric: "metric",
    Streak: "streak",
    Points: "points",
};
