/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A metric to create.
 */
export interface CreateMetricRequestItem {
    /** The metric name. */
    name: string;
    /** The metric key. */
    key: string;
    /** The metric unit type. Defaults to `number`. */
    unitType?: TrophyApi.CreateMetricRequestItemUnitType;
    /** For `unitType: currency`, this must be a supported `MetricCurrency` code such as `USD`. For `number`, this is an optional freeform unit label. */
    units?: string;
}
