"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateAchievementRequestItemTrigger = void 0;
/** The achievement trigger type. */
exports.CreateAchievementRequestItemTrigger = {
    Metric: "metric",
    Streak: "streak",
    Api: "api",
    Achievement: "achievement",
    Anniversary: "anniversary",
};
