/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A points system to create. Optionally include sub-entities.
 */
export interface CreatePointsSystemRequestItem {
    /** The points system name. */
    name: string;
    /** The points system key. Only alphanumeric characters, hyphens, and underscores are permitted. */
    key: string;
    /** A short description of the points system. */
    description?: string;
    /** An optional badge for the points system. */
    badge?: TrophyApi.CreatePointsSystemRequestItemBadge;
    /** Optional maximum points a user can earn. */
    maxPoints?: number;
    /** Optional array of levels to create alongside the system. */
    levels?: unknown[];
    /** Optional array of boosts to create alongside the system. */
    boosts?: unknown[];
    /** Optional array of triggers to create alongside the system. */
    triggers?: unknown[];
}
