/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The metric unit type.
 */
export declare type CreatedMetricUnitType = "number" | "currency";
export declare const CreatedMetricUnitType: {
    readonly Number: "number";
    readonly Currency: "currency";
};
