/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing deleted points system IDs and any per-item issues.
 */
export interface DeletePointsSystemsResponse {
    /** Array of deleted points system IDs. */
    deleted: TrophyApi.DeletedResource[];
    /** Array of issues encountered during deletion. */
    issues: TrophyApi.AdminIssue[];
}
