/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing the points triggers that were deleted and any per-item issues.
 */
export interface DeletePointsTriggersResponse {
    /** Array of deleted points triggers represented by ID. */
    deleted: TrophyApi.DeletedResource[];
    /** Array of issues encountered during trigger deletion. */
    issues: TrophyApi.AdminIssue[];
}
