/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A deleted resource represented by ID.
 */
export interface DeletedResource {
    /** The ID of the deleted resource. */
    id: string;
}
