/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing the points boosts that were deleted and any per-item issues.
 */
export interface DeletePointsBoostsResponse {
    /** Array of deleted points boosts represented by ID. */
    deleted: TrophyApi.DeletedResource[];
    /** Array of issues encountered during boost archival. */
    issues: TrophyApi.AdminIssue[];
}
