/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A soft-deleted resource represented by ID.
 */
export interface DeletedResource {
    /** The ID of the archived resource. */
    id: string;
}
