/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing deleted attributes represented by ID and any per-item issues, including invalid or missing attribute IDs.
 */
export interface DeleteAttributesResponse {
    /** Array of deleted attributes represented by ID. */
    deleted: TrophyApi.DeletedResource[];
    /** Array of issues encountered during attribute deletion. */
    issues: TrophyApi.AdminIssue[];
}
