/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing deleted leaderboards represented by ID and any per-item issues.
 */
export interface DeleteLeaderboardsResponse {
    /** Array of deleted leaderboards represented by ID. */
    deleted: TrophyApi.DeletedResource[];
    /** Array of issues encountered during leaderboard deletion. */
    issues: TrophyApi.AdminIssue[];
}
