/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface EventResponse {
    /** The unique ID of the event. */
    eventId: string;
    /** The unique ID of the metric that was updated. */
    metricId: string;
    /** The user's new total progress against the metric. */
    total: number;
    /** Achievements completed as a result of this event. */
    achievements: TrophyApi.UserAchievementResponse[];
    /** The user's current streak. */
    currentStreak: TrophyApi.MetricEventStreakResponse;
    /** A map of points systems by key. Only contains points systems that were affected by the event. */
    points: Record<string, TrophyApi.MetricEventPointsResponse>;
    /** A map of leaderboards by key. Only contains leaderboards that were affected by the event. */
    leaderboards: Record<string, TrophyApi.MetricEventLeaderboardResponse>;
    /** The idempotency key used for the event, if one was provided. */
    idempotencyKey?: string;
    /** Whether the event was replayed due to idempotency. */
    idempotentReplayed?: boolean;
}
