/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface EventResponseMetricsItem {
    /** The ID of the metric. */
    metricId?: string;
    /** A list of any new achievements that the user has now completed as a result of this event being submitted. */
    completed?: TrophyApi.MultiStageAchievementResponse[];
}
