/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface EventResponseMetricsItem {
    /** The trigger of the achievement, in this case either 'metric' or 'streak'. */
    trigger?: string;
    /** The ID of the metric that these achievements are associated with, if any. */
    metricId?: string;
    /** A list of any new achievements that the user has now completed as a result of this event being submitted. */
    completed: TrophyApi.EventResponseMetricsItemCompletedItem[];
}
