/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface GetUserPointsResponse {
    /** The ID of the points system */
    id: string;
    /** The name of the points system */
    name: string;
    /** The description of the points system */
    description?: string;
    /** The URL of the badge image for the points system */
    badgeUrl?: string;
    /** The user's total points */
    total: number;
    /** Array of trigger awards that added points. */
    awards: TrophyApi.PointsAward[];
}
