/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface GetUserPointsResponse {
    /** The user's total points */
    total?: number;
    /** Array of trigger awards that added points. */
    awards?: TrophyApi.PointsAward[];
}
