/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The status of the leaderboard.
 */
export declare type LeaderboardResponseWithRankingsStatus = "active" | "scheduled" | "finished";
export declare const LeaderboardResponseWithRankingsStatus: {
    readonly Active: "active";
    readonly Scheduled: "scheduled";
    readonly Finished: "finished";
};
