/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface LeaderboardResponseWithRankings extends TrophyApi.LeaderboardResponse {
    /** The status of the leaderboard. */
    status: TrophyApi.LeaderboardResponseWithRankingsStatus;
    /** Array of user rankings for the leaderboard. */
    rankings: TrophyApi.LeaderboardRanking[];
}
