/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A leaderboard event representing a change in a user's rank or value.
 */
export interface LeaderboardEvent {
    /** The timestamp when the event occurred. */
    timestamp?: Date;
    /** The user's rank before this event, or null if they were not on the leaderboard. */
    previousRank?: number;
    /** The user's rank after this event, or null if they are no longer on the leaderboard. */
    rank?: number;
    /** The user's value before this event, or null if they were not on the leaderboard. */
    previousValue?: number;
    /** The user's value after this event, or null if they are no longer on the leaderboard. */
    value?: number;
}
