"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LeaderboardResponseRankBy = void 0;
exports.LeaderboardResponseRankBy = {
    Points: "points",
    Streak: "streak",
    Metric: "metric",
};
