/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A paginated list of metrics.
 */
export declare type ListMetricsResponse = TrophyApi.CreatedMetric[];
