/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A paginated list of leaderboards.
 */
export declare type ListLeaderboardsResponse = TrophyApi.AdminLeaderboard[];
