/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing a list of points systems.
 */
export declare type ListPointsSystemsResponse = TrophyApi.AdminPointsSystem[];
