/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A paginated list of points levels.
 */
export declare type ListPointsLevelsResponse = TrophyApi.AdminPointsLevel[];
