/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Points system response for metric events. Unlike GetUserPointsResponse, this does not include boosts at the system level - boosts are only included in individual awards when they were applied.
 */
export interface MetricEventPointsResponse {
    /** The ID of the points system */
    id: string;
    /** The key of the points system */
    key: string;
    /** The name of the points system */
    name: string;
    /** The description of the points system */
    description?: string;
    /** The URL of the badge image for the points system */
    badgeUrl?: string;
    /** The maximum number of points a user can be awarded in this points system */
    maxPoints?: number;
    /** The user's total points */
    total: number;
    /** The points added by this event. */
    added: number;
    /** Array of trigger awards that added points. */
    awards: TrophyApi.PointsAward[];
}
