/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface MetricEventPointsResponse extends TrophyApi.GetUserPointsResponse {
    /** The points added by this event. */
    added?: number;
}
