/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface MetricResponse {
    /** The unique ID of the metric. */
    id: string;
    /** The unique key of the metric. */
    key: string;
    /** The name of the metric. */
    name: string;
    /** The status of the metric. */
    status: TrophyApi.MetricStatus;
    /** The user's current total for the metric. */
    current: number;
    /** A list of the metric's achievements and the user's progress towards each. */
    achievements: TrophyApi.MetricAchievementResponse[];
}
