"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationType = void 0;
exports.NotificationType = {
    AchievementCompleted: "achievement_completed",
    Recap: "recap",
    Reactivation: "reactivation",
    StreakReminder: "streak_reminder",
};
