/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A type of notification that can be configured.
 */
export declare type NotificationType = "achievement_completed" | "recap" | "reactivation" | "streak_reminder";
export declare const NotificationType: {
    readonly AchievementCompleted: "achievement_completed";
    readonly Recap: "recap";
    readonly Reactivation: "reactivation";
    readonly StreakReminder: "streak_reminder";
};
