/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A notification delivery channel.
 */
export declare type NotificationChannel = "email" | "push";
export declare const NotificationChannel: {
    readonly Email: "email";
    readonly Push: "push";
};
