"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationChannel = void 0;
/** A notification delivery channel. */
exports.NotificationChannel = {
    Email: "email",
    Push: "push",
};
