/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface OneOffAchievementResponse {
    /** The unique ID of the achievement. */
    id: string;
    /** The name of this achievement. */
    name?: string;
    /** The URL of the badge image for the achievement, if one has been uploaded. */
    badgeUrl?: string;
    /** The key used to reference this achievement in the API. */
    key?: string;
    /** The date and time the achievement was completed, in ISO 8601 format. */
    achievedAt?: Date;
}
