/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Array of points boost patches. Maximum 100 per request.
 */
export declare type PatchPointsBoostsRequest = TrophyApi.PatchPointsBoostsRequestItem[];
