/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Updated status.
 */
export declare type PatchPointsTriggersRequestItemStatus = "active" | "inactive";
export declare const PatchPointsTriggersRequestItemStatus: {
    readonly Active: "active";
    readonly Inactive: "inactive";
};
