"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PatchPointsTriggersRequestItemStatus = void 0;
exports.PatchPointsTriggersRequestItemStatus = {
    Active: "active",
    Inactive: "inactive",
};
