/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A metric patch object. `id` is required; `name`, `unitType`, and `units` are optional. `key` cannot be changed through this endpoint.
 */
export interface PatchMetricRequestItem {
    /** The UUID of the metric to patch. */
    id: string;
    /** The updated metric name. */
    name?: string;
    /** The updated metric unit type. */
    unitType?: TrophyApi.PatchMetricRequestItemUnitType;
    /** The updated units value. For `unitType: currency`, this must be a supported `MetricCurrency` code such as `USD`. */
    units?: string;
}
