/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Request body for patching metrics.
 */
export declare type PatchMetricsRequest = TrophyApi.PatchMetricRequestItem[];
