/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface PatchPointsBoostsRequestItem {
    /** The UUID of the boost to update. */
    id: string;
    /** Updated name for the boost. */
    name?: string;
    /** Updated start date (YYYY-MM-DD). */
    start?: string;
    /** Updated end date (YYYY-MM-DD) or null to remove end date. */
    end?: string;
    /** Updated points multiplier. */
    multiplier?: number;
    /** Updated rounding strategy. */
    rounding?: TrophyApi.PatchPointsBoostsRequestItemRounding;
    /** Updated user attribute filters. Cannot be set on user-specific boosts. Set to null to clear. */
    userAttributes?: TrophyApi.PatchPointsBoostsRequestItemUserAttributesItem[];
}
