"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PatchPointsTriggersRequestItemType = void 0;
exports.PatchPointsTriggersRequestItemType = {
    Metric: "metric",
    Achievement: "achievement",
    Streak: "streak",
    Time: "time",
    UserCreation: "user_creation",
};
