/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface PatchPointsLevelsRequestItem {
    /** The UUID of the level to update. */
    id: string;
    /** The updated level name. */
    name?: string;
    /** The updated threshold points value. */
    points?: number;
    /** The updated level description. */
    description?: string;
    /** The updated badge, or `null` to clear it. */
    badge?: TrophyApi.PatchPointsLevelsRequestItemBadge;
}
