"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PatchPointsTriggersRequestItemTimeUnit = void 0;
/** Updated time unit. Only permitted for time triggers. */
exports.PatchPointsTriggersRequestItemTimeUnit = {
    Hours: "hours",
    Days: "days",
};
