/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Updated time unit. Only permitted for time triggers.
 */
export declare type PatchPointsTriggersRequestItemTimeUnit = "hours" | "days";
export declare const PatchPointsTriggersRequestItemTimeUnit: {
    readonly Hours: "hours";
    readonly Days: "days";
};
