/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Array of points level patches. Maximum 100 per request.
 */
export declare type PatchPointsLevelsRequest = TrophyApi.PatchPointsLevelsRequestItem[];
