/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The updated metric unit type.
 */
export declare type PatchMetricRequestItemUnitType = "number" | "currency";
export declare const PatchMetricRequestItemUnitType: {
    readonly Number: "number";
    readonly Currency: "currency";
};
