/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface PatchPointsTriggersRequestItem {
    /** The UUID of the trigger to update. */
    id: string;
    /** Updated trigger type. Can only be changed when the trigger is inactive. Required fields for the new type must be provided. */
    type?: TrophyApi.PatchPointsTriggersRequestItemType;
    /** Updated points value. */
    points?: number;
    /** Updated status. */
    status?: TrophyApi.PatchPointsTriggersRequestItemStatus;
    /** Updated user attribute filters. Set to null to clear. */
    userAttributes?: TrophyApi.PatchPointsTriggersRequestItemUserAttributesItem[];
    /** Updated metric ID. Only permitted for metric triggers. */
    metricId?: string;
    /** Updated metric threshold. Only permitted for metric triggers. */
    metricThreshold?: number;
    /** Updated event attribute filters. Only permitted for metric triggers. Set to null to clear. */
    eventAttributes?: TrophyApi.PatchPointsTriggersRequestItemEventAttributesItem[];
    /** Updated achievement ID. Only permitted for achievement triggers. */
    achievementId?: string;
    /** Updated streak length. Only permitted for streak triggers. */
    streakLength?: number;
    /** Updated time unit. Only permitted for time triggers. */
    timeUnit?: TrophyApi.PatchPointsTriggersRequestItemTimeUnit;
    /** Updated time interval. Only permitted for time triggers. */
    timeInterval?: number;
    /** Updated block-if-out-of-points setting. */
    blockIfOutOfPoints?: boolean;
}
