/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface PointsSystemResponse {
    /** The unique ID of the points system. */
    id: string;
    /** The name of the points system. */
    name: string;
    /** The description of the points system. */
    description?: string;
    /** The URL of the badge image for the points system, if one has been uploaded. */
    badgeUrl?: string;
    /** The maximum number of points a user can be awarded in this points system */
    maxPoints?: number;
    /** Array of active triggers for this points system. */
    triggers: TrophyApi.PointsTriggerResponse[];
}
