/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of trigger.
 */
export declare type PointsTriggerResponseType = "metric" | "achievement" | "streak";
export declare const PointsTriggerResponseType: {
    readonly Metric: "metric";
    readonly Achievement: "achievement";
    readonly Streak: "streak";
};
