/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface PointsTrigger {
    /** The ID of the trigger */
    id?: string;
    /** The type of trigger */
    type?: TrophyApi.PointsTriggerType;
    /** The points awarded by this trigger. */
    points?: number;
    /** If the trigger has type 'metric', the name of the metric */
    metricName?: string;
    /** If the trigger has type 'metric', the threshold of the metric that triggers the points */
    metricThreshold?: number;
    /** If the trigger has type 'streak', the threshold of the streak that triggers the points */
    streakLengthThreshold?: number;
    /** If the trigger has type 'achievement', the name of the achievement */
    achievementName?: string;
}
