/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A breakdown of users by level in a points system.
 */
export declare type PointsLevelSummaryResponse = TrophyApi.PointsLevelSummaryResponseItem[];
