/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A level within a points system.
 */
export interface PointsLevel {
    /** The ID of the level */
    id: string;
    /** The unique key of the level */
    key: string;
    /** The name of the level */
    name: string;
    /** The description of the level */
    description: string;
    /** The URL of the badge image for the level */
    badgeUrl?: string;
    /** The points threshold required to reach this level */
    points: number;
}
