/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PointsTriggerResponseUserAttributesItem {
    /** The key of the user attribute. */
    key: string;
    /** The value of the user attribute. */
    value: string;
}
