/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Points boost payload sent in points.boost_started and points.boost_finished webhook events.
 */
export interface PointsBoostWebhookPayload {
    /** The ID of the points boost. */
    id: string;
    /** The name of the points boost. */
    name: string;
    /** The status of the points boost. */
    status: TrophyApi.PointsBoostWebhookPayloadStatus;
    /** The customer-facing user ID that the boost is scoped to, or null for global boosts. */
    userId?: string;
    /** The ID of the points system this boost applies to. */
    pointsSystemId: string;
    /** The key of the points system this boost applies to. */
    pointsSystemKey: string;
    /** The name of the points system this boost applies to. */
    pointsSystemName: string;
    /** The start date of the points boost (YYYY-MM-DD). */
    start: string;
    /** The end date of the points boost (YYYY-MM-DD), or null if open-ended. */
    end?: string;
    /** The multiplier applied to points during the boost. */
    multiplier: number;
    /** The rounding method applied to boosted points. */
    rounding: TrophyApi.PointsBoostWebhookPayloadRounding;
}
