"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PointsTriggerStatus = void 0;
/** The status of the trigger. */
exports.PointsTriggerStatus = {
    Active: "active",
    Inactive: "inactive",
    Archived: "archived",
};
