/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Deprecated. Event attribute filter that must be met for this trigger to award points. Only present if the trigger has an event filter configured.
 */
export interface PointsTriggerEventAttribute {
    /** The key of the event attribute. */
    key: string;
    /** The required value of the event attribute. */
    value: string;
}
