/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The status of the trigger.
 */
export declare type PointsTriggerStatus = "active" | "inactive" | "archived";
export declare const PointsTriggerStatus: {
    readonly Active: "active";
    readonly Inactive: "inactive";
    readonly Archived: "archived";
};
