/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Event attribute filter that must be met for this trigger to activate. Only present if the trigger has an event filter configured.
 */
export interface PointsTriggerResponseEventAttribute {
    /** The key of the event attribute. */
    key: string;
    /** The required value of the event attribute. */
    value: string;
}
