"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PointsBoostRounding = void 0;
/** The rounding method of the points boost */
exports.PointsBoostRounding = {
    Down: "down",
    Up: "up",
    Nearest: "nearest",
};
