"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PointsTriggerTimeUnit = void 0;
/** If the trigger has type 'time', the unit of time after which to award points */
exports.PointsTriggerTimeUnit = {
    Hour: "hour",
    Day: "day",
};
