/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PointsTriggerResponseEventAttributesItem {
    /** The key of the event attribute. */
    key: string;
    /** The required value of the event attribute. */
    value: string;
}
