/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PointsRange {
    /** The start of the points range. Inclusive. */
    from: number;
    /** The end of the points range. Inclusive. */
    to: number;
    /** The number of users in this points range. */
    users: number;
}
