"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PointsBoostWebhookPayloadStatus = void 0;
/** The status of the points boost. */
exports.PointsBoostWebhookPayloadStatus = {
    Active: "active",
    Finished: "finished",
};
