/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The rounding method of the points boost
 */
export declare type PointsBoostRounding = "down" | "up" | "nearest";
export declare const PointsBoostRounding: {
    readonly Down: "down";
    readonly Up: "up";
    readonly Nearest: "nearest";
};
