/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing restored users and any issues encountered.
 */
export interface RestoreStreaksResponse {
    /** Array of user IDs whose streaks were successfully restored. */
    restoredUsers: string[];
    /** Array of issues encountered during streak restoration. */
    issues: TrophyApi.BulkInsertIssue[];
}
