/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type StreakFrequency = "daily" | "weekly" | "monthly" | "yearly";
export declare const StreakFrequency: {
    readonly Daily: "daily";
    readonly Weekly: "weekly";
    readonly Monthly: "monthly";
    readonly Yearly: "yearly";
};
