/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface StreakResponse {
    /** The length of the user's current streak. */
    length: number;
    /** The frequency of the streak. */
    frequency: TrophyApi.StreakFrequency;
}
