/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether meeting any single metric threshold (`OR`) or all configured metric thresholds (`AND`) extends the user's streak. Matches the evaluation mode configured in dashboard streak settings.
 */
export declare type StreakEvaluationModePreference = "OR" | "AND";
export declare const StreakEvaluationModePreference: {
    readonly Or: "OR";
    readonly And: "AND";
};
