/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An object representing a past streak period.
 */
export interface StreakResponseStreakHistoryItem {
    /** The date this streak period started. */
    periodStart: string;
    /** The date this streak period ended. */
    periodEnd: string;
    /** The length of the user's streak during this period. */
    length: number;
    /** Whether the user used a streak freeze during this period. Only present if the organization has enabled streak freezes. */
    usedFreeze?: boolean;
}
