"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateAchievementRequestItemStatus = void 0;
/** The updated status. */
exports.UpdateAchievementRequestItemStatus = {
    Active: "active",
    Inactive: "inactive",
    Locked: "locked",
};
