"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateLeaderboardRequestItemStatus = void 0;
/** The target user-facing status. `scheduled` activates a leaderboard whose start date is in the future. `finished` behaves like the dashboard finish action. */
exports.UpdateLeaderboardRequestItemStatus = {
    Inactive: "inactive",
    Active: "active",
    Scheduled: "scheduled",
    Finished: "finished",
};
