/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An attribute update object. `id` is required and `name` is optional. `key` and `type` cannot be changed through this endpoint.
 */
export interface UpdateAttributeRequestItem {
    /** The UUID of the attribute to update. */
    id: string;
    /** The updated attribute name. */
    name?: string;
}
