/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Response containing updated tenants and any issues.
 */
export interface UpdateTenantsResponse {
    /** Array of successfully updated tenants. */
    updated: TrophyApi.AdminTenant[];
    /** Array of issues encountered during update. */
    issues: TrophyApi.AdminIssue[];
}
