"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateLeaderboardRequestItemRankBy = void 0;
exports.UpdateLeaderboardRequestItemRankBy = {
    Metric: "metric",
    Streak: "streak",
    Points: "points",
};
