/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * Request body for updating attributes.
 */
export declare type UpdateAttributesRequest = TrophyApi.UpdateAttributeRequestItem[];
