"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateMetricRequestItemUnitType = void 0;
/** The updated metric unit type. */
exports.UpdateMetricRequestItemUnitType = {
    Number: "number",
    Currency: "currency",
};
