"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateLeaderboardRequestItemRankBy = void 0;
/** The updated ranking criterion. This can only be changed while the leaderboard is inactive. */
exports.UpdateLeaderboardRequestItemRankBy = {
    Metric: "metric",
    Streak: "streak",
    Points: "points",
};
