"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateAchievementRequestItemTrigger = void 0;
/** The updated trigger type. Changing trigger requires the new trigger's mandatory fields. */
exports.UpdateAchievementRequestItemTrigger = {
    Metric: "metric",
    Streak: "streak",
    Api: "api",
    Achievement: "achievement",
    Anniversary: "anniversary",
};
