/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The target status. `active` and `inactive` behave the same as the dashboard activate, schedule, deactivate, and finish actions.
 */
export declare type UpdateLeaderboardRequestItemStatus = "active" | "inactive";
export declare const UpdateLeaderboardRequestItemStatus: {
    readonly Active: "active";
    readonly Inactive: "inactive";
};
