"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateLeaderboardRequestItemStatus = void 0;
exports.UpdateLeaderboardRequestItemStatus = {
    Inactive: "inactive",
    Active: "active",
    Scheduled: "scheduled",
    Finished: "finished",
};
