/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UpdateLeaderboardRequestItemRunUnit = "day" | "month" | "year";
export declare const UpdateLeaderboardRequestItemRunUnit: {
    readonly Day: "day";
    readonly Month: "month";
    readonly Year: "year";
};
