/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * An object with editable user fields.
 */
export interface UpsertedUser extends TrophyApi.UpdatedUser {
    /** The ID of the user in your database. Must be a string. */
    id: string;
}
