/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A user of your application.
 */
export interface User extends TrophyApi.UpsertedUser {
    /** Whether the user is in the control group, meaning they do not receive emails or other communications from Trophy. */
    control: boolean;
    /** The date and time the user was created, in ISO 8601 format. */
    created: Date;
    /** The date and time the user was last updated, in ISO 8601 format. */
    updated: Date;
}
