/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A user's preferences.
 */
export interface UserPreferencesResponse {
    notifications: TrophyApi.NotificationPreferences;
}
