/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A user's data for a specific leaderboard including rank, value, and history.
 */
export interface UserLeaderboardResponse extends TrophyApi.LeaderboardResponse {
    /** The user's current rank in this leaderboard. Null if the user is not on the leaderboard. */
    rank?: number;
    /** The user's current value in this leaderboard. Null if the user is not on the leaderboard. */
    value?: number;
    /** An array of events showing the user's rank and value changes over time. */
    history: TrophyApi.LeaderboardEvent[];
}
