/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface WebhooksStreakFreezeConsumedPayload {
    /** The webhook event type. */
    type: "streak.freeze_consumed";
    /** The user whose streak freeze was consumed. */
    user: TrophyApi.User;
    /** The number of freezes consumed. */
    consumed: number;
    /** The total number of freezes the user has left after the consumption. */
    freezes: number;
}
