/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * The points system in which the level changed.
 */
export interface WebhooksPointsLevelChangedPayloadPoints extends TrophyApi.PointsResponse {
    /** The user's total points in this system. */
    total: number;
}
