/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface WebhooksLeaderboardStartedPayload {
    /** The webhook event type. */
    type: "leaderboard.started";
    /** The leaderboard run that started and its initial rankings. */
    leaderboard: TrophyApi.LeaderboardResponseWithRankings;
}
