/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
export interface WebhooksStreakFreezeEarnedPayload {
    /** The webhook event type. */
    type: "streak.freeze_earned";
    /** The user who earned streak freezes. */
    user: TrophyApi.User;
    /** The number of freezes earned. */
    earned: number;
    /** The total number of freezes the user has after the event. */
    freezes: number;
}
