/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * A user's data for a specific leaderboard including rank, value, and history.
 */
export interface WebhookUserLeaderboardResponse extends TrophyApi.UserLeaderboardResponse {
    /** The user's rank before this event, or null if they were not on the leaderboard. */
    previousRank?: number;
    /** The user's value before this event, or null if they were not on the leaderboard. */
    previousValue?: number;
}
