/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "..";
/**
 * The user's most active month during the year.
 */
export interface WrappedMostActiveMonth extends TrophyApi.WrappedActivityPeriod {
    /** The month number (0-11, where 0 is January). */
    month: number;
}
