/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A user's points data for a wrapped period.
 */
export interface WrappedPoints {
    /** The name of the points system. */
    name: string;
    /** The description of the points system. */
    description?: string;
    /** The user's current total points. */
    currentTotal: number;
    /** The change in points during the period. */
    changeThisPeriod: number;
    /** The percentage change in points during the period. */
    percentChange: number;
    /** The user's percentile rank for this points system during the period. Only included for weekly, monthly, and yearly aggregation periods. */
    percentileThisPeriod?: number;
}
