/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         notifications: {
 *             streakReminder: [TrophyApi.NotificationChannel.Email]
 *         }
 *     }
 *
 * @example
 *     {
 *         notifications: {
 *             recap: [TrophyApi.NotificationChannel.Email]
 *         }
 *     }
 *
 * @example
 *     {
 *         notifications: {
 *             achievementCompleted: [TrophyApi.NotificationChannel.Email, TrophyApi.NotificationChannel.Push]
 *         }
 *     }
 *
 * @example
 *     {
 *         streak: {
 *             evaluationMode: TrophyApi.StreakEvaluationModePreference.Or,
 *             metrics: [{
 *                     key: "words-written",
 *                     threshold: 500
 *                 }]
 *         }
 *     }
 */
export interface UpdateUserPreferencesRequest {
    notifications?: TrophyApi.NotificationPreferences;
    streak?: TrophyApi.StreakPreferences;
}
