/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface UsersPointsRequest {
    /**
     * The number of recent point awards to return.
     */
    awards?: number;
}
