/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         aggregation: TrophyApi.UsersPointsEventSummaryRequestAggregation.Daily,
 *         startDate: "2024-01-01",
 *         endDate: "2024-01-31"
 *     }
 */
export interface UsersPointsEventSummaryRequest {
    /**
     * The time period over which to aggregate the event data.
     */
    aggregation: TrophyApi.UsersPointsEventSummaryRequestAggregation;
    /**
     * The start date for the data range in YYYY-MM-DD format. The startDate must be before the endDate, and the date range must not exceed 400 days.
     */
    startDate: string;
    /**
     * The end date for the data range in YYYY-MM-DD format. The endDate must be after the startDate, and the date range must not exceed 400 days.
     */
    endDate: string;
}
