/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         historyPeriods: 1
 *     }
 */
export interface UsersStreakRequest {
    /**
     * The number of past streak periods to include in the streakHistory field of the  response.
     */
    historyPeriods?: number;
}
