/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         includeIncomplete: "true"
 *     }
 */
export interface UsersAchievementsRequest {
    /**
     * When set to 'true', returns both completed and incomplete achievements for the user. When omitted or set to any other value, returns only completed achievements.
     */
    includeIncomplete?: "true";
}
