"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Admin = void 0;
const Client_1 = require("../resources/streaks/client/Client");
class Admin {
    constructor(_options) {
        this._options = _options;
    }
    get streaks() {
        var _a;
        return ((_a = this._streaks) !== null && _a !== void 0 ? _a : (this._streaks = new Client_1.Streaks(this._options)));
    }
}
exports.Admin = Admin;
