"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Admin = void 0;
const Client_1 = require("../resources/streaks/client/Client");
const Client_2 = require("../resources/metrics/client/Client");
const Client_3 = require("../resources/points/client/Client");
class Admin {
    constructor(_options) {
        this._options = _options;
    }
    get streaks() {
        var _a;
        return ((_a = this._streaks) !== null && _a !== void 0 ? _a : (this._streaks = new Client_1.Streaks(this._options)));
    }
    get metrics() {
        var _a;
        return ((_a = this._metrics) !== null && _a !== void 0 ? _a : (this._metrics = new Client_2.Metrics(this._options)));
    }
    get points() {
        var _a;
        return ((_a = this._points) !== null && _a !== void 0 ? _a : (this._points = new Client_3.Points(this._options)));
    }
}
exports.Admin = Admin;
