/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../../../../..";
export interface CreatePointsBoostsRequestBoostsItem {
    /** The ID of the user to create a boost for. */
    userId: string;
    /** The name of the boost. */
    name: string;
    /** The start date of the boost (YYYY-MM-DD). */
    start: string;
    /** The end date of the boost (YYYY-MM-DD). If null, the boost has no end date. */
    end?: string;
    /** The points multiplier. Must be greater than 0, not equal to 1, and less than 100. */
    multiplier: number;
    /** How to round the boosted points. Defaults to 'down'. */
    rounding?: TrophyApi.admin.points.CreatePointsBoostsRequestBoostsItemRounding;
}
