/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * How to round the boosted points. Defaults to 'down'.
 */
export declare type CreatePointsBoostsRequestBoostsItemRounding = "down" | "up" | "nearest";
export declare const CreatePointsBoostsRequestBoostsItemRounding: {
    readonly Down: "down";
    readonly Up: "up";
    readonly Nearest: "nearest";
};
