/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface MetricsDeleteRequest {
    /**
     * Metric IDs to delete. Repeat the query param or provide a comma-separated list.
     */
    ids?: string | string[];
}
