/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TrophyApi from "../../../../..";
export declare namespace Tenants {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
        tenantId?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Tenants {
    protected readonly _options: Tenants.Options;
    constructor(_options: Tenants.Options);
    /**
     * List tenants in the current environment.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.tenants.list({
     *         limit: 1,
     *         skip: 1
     *     })
     */
    list(request?: TrophyApi.admin.TenantsListRequest, requestOptions?: Tenants.RequestOptions): Promise<TrophyApi.ListTenantsResponse>;
    /**
     * Create tenants.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.tenants.create([{
     *             customerId: "customer_12345",
     *             name: "Acme Corp"
     *         }, {
     *             customerId: "customer_67890",
     *             name: "Globex Inc"
     *         }])
     */
    create(request: TrophyApi.CreateTenantsRequest, requestOptions?: Tenants.RequestOptions): Promise<TrophyApi.CreateTenantsResponse>;
    /**
     * Delete tenants by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.tenants.delete({})
     */
    delete(request?: TrophyApi.admin.TenantsDeleteRequest, requestOptions?: Tenants.RequestOptions): Promise<TrophyApi.DeleteTenantsResponse>;
    /**
     * Update tenants by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.tenants.update([{
     *             id: "550e8400-e29b-41d4-a716-446655440000",
     *             name: "Acme Corporation"
     *         }])
     */
    update(request: TrophyApi.UpdateTenantsRequest, requestOptions?: Tenants.RequestOptions): Promise<TrophyApi.UpdateTenantsResponse>;
    /**
     * Get a tenant by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.tenants.get("550e8400-e29b-41d4-a716-446655440000")
     */
    get(id: string, requestOptions?: Tenants.RequestOptions): Promise<TrophyApi.AdminTenant>;
}
