/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as TrophyApi from "../../..";
export declare namespace Users {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Users {
    protected readonly _options: Users.Options;
    constructor(_options: Users.Options);
    /**
     * Create a new user.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.create({
     *         id: "user-id"
     *     })
     */
    create(request: TrophyApi.UpsertedUser, requestOptions?: Users.RequestOptions): Promise<TrophyApi.User>;
    /**
     * Get a single user.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.get("userId")
     */
    get(id: string, requestOptions?: Users.RequestOptions): Promise<TrophyApi.User>;
    /**
     * Identify a user.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.identify("id", {
     *         email: "user@example.com",
     *         tz: "Europe/London",
     *         attributes: {
     *             "department": "engineering",
     *             "role": "developer"
     *         }
     *     })
     */
    identify(id: string, request: TrophyApi.UpdatedUser, requestOptions?: Users.RequestOptions): Promise<TrophyApi.User>;
    /**
     * Update a user.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.update("id", {
     *         email: "user@example.com",
     *         tz: "Europe/London",
     *         attributes: {
     *             "department": "engineering",
     *             "role": "developer"
     *         }
     *     })
     */
    update(id: string, request: TrophyApi.UpdatedUser, requestOptions?: Users.RequestOptions): Promise<TrophyApi.User>;
    /**
     * Get a single user's progress against all active metrics.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.allMetrics("userId")
     */
    allMetrics(id: string, requestOptions?: Users.RequestOptions): Promise<TrophyApi.MetricResponse[]>;
    /**
     * Get a user's progress against a single active metric.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.singleMetric("userId", "key")
     */
    singleMetric(id: string, key: string, requestOptions?: Users.RequestOptions): Promise<TrophyApi.MetricResponse>;
    /**
     * Get a summary of metric events over time for a user.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.metricEventSummary("userId", "words-written", {
     *         aggregation: TrophyApi.UsersMetricEventSummaryRequestAggregation.Daily,
     *         startDate: "2024-01-01",
     *         endDate: "2024-01-31"
     *     })
     */
    metricEventSummary(id: string, key: string, request: TrophyApi.UsersMetricEventSummaryRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.UsersMetricEventSummaryResponseItem[]>;
    /**
     * Get a user's achievements.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.achievements("userId", {
     *         includeIncomplete: "true"
     *     })
     */
    achievements(id: string, request?: TrophyApi.UsersAchievementsRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.CompletedAchievementResponse[]>;
    /**
     * Get a user's streak data.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.streak("userId", {
     *         historyPeriods: 1
     *     })
     */
    streak(id: string, request?: TrophyApi.UsersStreakRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.StreakResponse>;
    /**
     * Get a user's points for a specific points system.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.points("userId", "points-system-key", {
     *         awards: 1
     *     })
     */
    points(id: string, key: string, request?: TrophyApi.UsersPointsRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.GetUserPointsResponse>;
    /**
     * Get a summary of points awards over time for a user for a specific points system.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.pointsEventSummary("userId", "points-system-key", {
     *         aggregation: TrophyApi.UsersPointsEventSummaryRequestAggregation.Daily,
     *         startDate: "2024-01-01",
     *         endDate: "2024-01-31"
     *     })
     */
    pointsEventSummary(id: string, key: string, request: TrophyApi.UsersPointsEventSummaryRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.UsersPointsEventSummaryResponseItem[]>;
    /**
     * Get a user's rank, value, and history for a specific leaderboard.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.leaderboard("user-123", "weekly-words", {
     *         run: "2025-01-15",
     *         numEvents: 1
     *     })
     */
    leaderboard(id: string, key: string, request?: TrophyApi.UsersLeaderboardRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.UserLeaderboardResponseWithHistory>;
    /**
     * Get a user's year-in-review wrapped data.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.users.wrapped("user-123", {
     *         year: 1
     *     })
     */
    wrapped(id: string, request?: TrophyApi.UsersWrappedRequest, requestOptions?: Users.RequestOptions): Promise<TrophyApi.WrappedResponse>;
}
