/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import { Freezes } from "../resources/freezes/client/Client";
export declare namespace Streaks {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Streaks {
    protected readonly _options: Streaks.Options;
    constructor(_options: Streaks.Options);
    protected _freezes: Freezes | undefined;
    get freezes(): Freezes;
}
