"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Streaks = void 0;
const Client_1 = require("../resources/freezes/client/Client");
class Streaks {
    constructor(_options) {
        this._options = _options;
    }
    get freezes() {
        var _a;
        return ((_a = this._freezes) !== null && _a !== void 0 ? _a : (this._freezes = new Client_1.Freezes(this._options)));
    }
}
exports.Streaks = Streaks;
