/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TrophyApi from "../../../../..";
import { Freezes } from "../resources/freezes/client/Client";
export declare namespace Streaks {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Streaks {
    protected readonly _options: Streaks.Options;
    constructor(_options: Streaks.Options);
    /**
     * Restore streaks for multiple users to the maximum previously achieved streak length found within the current restore window: the last 90 days for daily streaks, weekly periods starting with the week containing the start of the current calendar year for weekly streaks, and monthly periods starting at the beginning of the previous calendar year for monthly streaks.
     * @throws {@link TrophyApi.BadRequestError}
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.streaks.restore({
     *         users: [{
     *                 id: "user-123"
     *             }, {
     *                 id: "user-456"
     *             }]
     *     })
     *
     * @example
     *     await trophyApi.admin.streaks.restore({
     *         users: [{
     *                 id: "user-123"
     *             }, {
     *                 id: "user-456"
     *             }]
     *     })
     */
    restore(request: TrophyApi.admin.RestoreStreaksRequest, requestOptions?: Streaks.RequestOptions): Promise<TrophyApi.RestoreStreaksResponse>;
    protected _freezes: Freezes | undefined;
    get freezes(): Freezes;
}
