/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TrophyApi from "../../../../..";
export declare namespace Leaderboards {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Leaderboards {
    protected readonly _options: Leaderboards.Options;
    constructor(_options: Leaderboards.Options);
    /**
     * List leaderboards.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.leaderboards.list({
     *         limit: 1,
     *         skip: 1
     *     })
     */
    list(request?: TrophyApi.admin.LeaderboardsListRequest, requestOptions?: Leaderboards.RequestOptions): Promise<TrophyApi.ListLeaderboardsResponse>;
    /**
     * Create leaderboards. Maximum 100 leaderboards per request.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.leaderboards.create([{
     *             name: "Revenue Champions",
     *             key: "revenue-champions",
     *             status: TrophyApi.CreateLeaderboardRequestItemStatus.Inactive,
     *             rankBy: TrophyApi.CreateLeaderboardRequestItemRankBy.Metric,
     *             metricId: "550e8400-e29b-41d4-a716-446655440000",
     *             maxParticipants: 100,
     *             start: "2026-04-20",
     *             breakdownAttributes: ["550e8400-e29b-41d4-a716-446655440010"],
     *             runUnit: TrophyApi.CreateLeaderboardRequestItemRunUnit.Month,
     *             runInterval: 1
     *         }, {
     *             name: "Streak Legends",
     *             key: "streak-legends",
     *             status: TrophyApi.CreateLeaderboardRequestItemStatus.Scheduled,
     *             rankBy: TrophyApi.CreateLeaderboardRequestItemRankBy.Streak,
     *             start: "2026-04-27"
     *         }])
     */
    create(request: TrophyApi.CreateLeaderboardsRequest, requestOptions?: Leaderboards.RequestOptions): Promise<TrophyApi.CreateLeaderboardsResponse>;
    /**
     * Delete leaderboards by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.leaderboards.delete({})
     */
    delete(request?: TrophyApi.admin.LeaderboardsDeleteRequest, requestOptions?: Leaderboards.RequestOptions): Promise<TrophyApi.DeleteLeaderboardsResponse>;
    /**
     * Update leaderboards by ID. Updating `status` behaves the same as activating, scheduling, deactivating, or finishing a leaderboard in the dashboard.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.leaderboards.update([{
     *             id: "550e8400-e29b-41d4-a716-446655440100",
     *             name: "Monthly Revenue Champions",
     *             description: "Ranked by monthly revenue",
     *             status: TrophyApi.UpdateLeaderboardRequestItemStatus.Active
     *         }, {
     *             id: "550e8400-e29b-41d4-a716-446655440101",
     *             status: TrophyApi.UpdateLeaderboardRequestItemStatus.Finished
     *         }])
     */
    update(request: TrophyApi.UpdateLeaderboardsRequest, requestOptions?: Leaderboards.RequestOptions): Promise<TrophyApi.UpdateLeaderboardsResponse>;
    /**
     * Get a leaderboard by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.leaderboards.get("550e8400-e29b-41d4-a716-446655440100")
     *
     * @example
     *     await trophyApi.admin.leaderboards.get("550e8400-e29b-41d4-a716-446655440100")
     */
    get(id: string, requestOptions?: Leaderboards.RequestOptions): Promise<TrophyApi.AdminLeaderboard>;
}
