/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface StreaksListRequest {
    /**
     * A list of up to 100 user IDs.
     */
    userIds?: string | string[];
}
