/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         limit: 1,
 *         type: TrophyApi.StreaksRankingsRequestType.Active
 *     }
 */
export interface StreaksRankingsRequest {
    /**
     * Number of users to return. Must be between 1 and 100.
     */
    limit?: number;
    /**
     * Whether to rank users by active streaks or longest streaks ever achieved.
     */
    type?: TrophyApi.StreaksRankingsRequestType;
}
