/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as TrophyApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AchievementsCompleteRequest: core.serialization.Schema<serializers.AchievementsCompleteRequest.Raw, TrophyApi.AchievementsCompleteRequest>;
export declare namespace AchievementsCompleteRequest {
    interface Raw {
        user: serializers.EventRequestUser.Raw;
    }
}
