/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TrophyApi from "../../../../..";
export declare namespace Metrics {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Metrics {
    protected readonly _options: Metrics.Options;
    constructor(_options: Metrics.Options);
    /**
     * List metrics.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.metrics.list({
     *         limit: 1,
     *         skip: 1
     *     })
     */
    list(request?: TrophyApi.admin.MetricsListRequest, requestOptions?: Metrics.RequestOptions): Promise<TrophyApi.ListMetricsResponse>;
    /**
     * Create metrics.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.metrics.create([{
     *             name: "Invites Sent",
     *             key: "invites-sent"
     *         }, {
     *             name: "Revenue",
     *             key: "revenue",
     *             unitType: TrophyApi.CreateMetricRequestItemUnitType.Currency,
     *             units: "USD"
     *         }])
     */
    create(request: TrophyApi.CreateMetricsRequest, requestOptions?: Metrics.RequestOptions): Promise<TrophyApi.CreateMetricsResponse>;
    /**
     * Delete metrics by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.metrics.delete({})
     */
    delete(request?: TrophyApi.admin.MetricsDeleteRequest, requestOptions?: Metrics.RequestOptions): Promise<TrophyApi.DeleteMetricsResponse>;
    /**
     * Update metrics by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.metrics.update([{
     *             id: "550e8400-e29b-41d4-a716-446655440000",
     *             name: "Invites Completed",
     *             units: "invites"
     *         }, {
     *             id: "550e8400-e29b-41d4-a716-446655440001",
     *             unitType: TrophyApi.UpdateMetricRequestItemUnitType.Number,
     *             units: "dollars"
     *         }])
     *
     * @example
     *     await trophyApi.admin.metrics.update([{
     *             id: "550e8400-e29b-41d4-a716-446655440000",
     *             name: "Invites Completed",
     *             units: "invites"
     *         }, {
     *             id: "550e8400-e29b-41d4-a716-446655440001",
     *             unitType: TrophyApi.UpdateMetricRequestItemUnitType.Number,
     *             units: "dollars"
     *         }])
     */
    update(request: TrophyApi.UpdateMetricsRequest, requestOptions?: Metrics.RequestOptions): Promise<TrophyApi.UpdateMetricsResponse>;
    /**
     * Get a metric by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.metrics.get("550e8400-e29b-41d4-a716-446655440000")
     *
     * @example
     *     await trophyApi.admin.metrics.get("550e8400-e29b-41d4-a716-446655440000")
     */
    get(id: string, requestOptions?: Metrics.RequestOptions): Promise<TrophyApi.CreatedMetric>;
}
