/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface SystemsDeleteRequest {
    /**
     * The IDs of the points systems to delete.
     */
    ids?: string | string[];
}
