/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../../../environments";
import * as core from "../../../../../../../../core";
import * as TrophyApi from "../../../../../../..";
export declare namespace Triggers {
    interface Options {
        environment?: core.Supplier<environments.TrophyApiEnvironment | environments.TrophyApiEnvironmentUrls>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Triggers {
    protected readonly _options: Triggers.Options;
    constructor(_options: Triggers.Options);
    /**
     * List points triggers for a system.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.triggers.list("550e8400-e29b-41d4-a716-446655440000", {
     *         limit: 1,
     *         skip: 1
     *     })
     */
    list(systemId: string, request?: TrophyApi.admin.points.TriggersListRequest, requestOptions?: Triggers.RequestOptions): Promise<TrophyApi.ListPointsTriggersResponse>;
    /**
     * Create points triggers in bulk. Maximum 100 triggers per request.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.triggers.create("550e8400-e29b-41d4-a716-446655440000", [{
     *             type: TrophyApi.CreatePointsTriggersRequestItemType.Metric,
     *             points: 10
     *         }])
     */
    create(systemId: string, request: TrophyApi.CreatePointsTriggersRequest, requestOptions?: Triggers.RequestOptions): Promise<TrophyApi.CreatePointsTriggersResponse>;
    /**
     * Delete (archive) points triggers by ID. Maximum 100 trigger IDs per request.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.triggers.delete(undefined, {})
     */
    delete(systemId: string, request?: TrophyApi.admin.points.TriggersDeleteRequest, requestOptions?: Triggers.RequestOptions): Promise<TrophyApi.DeletePointsTriggersResponse>;
    /**
     * Update points triggers in bulk. Maximum 100 triggers per request. Only provided fields are updated; omitted fields are preserved.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.triggers.update("550e8400-e29b-41d4-a716-446655440000", [{
     *             id: "id"
     *         }])
     */
    update(systemId: string, request: TrophyApi.PatchPointsTriggersRequest, requestOptions?: Triggers.RequestOptions): Promise<TrophyApi.PatchPointsTriggersResponse>;
    /**
     * Get a single points trigger by ID.
     * @throws {@link TrophyApi.UnauthorizedError}
     * @throws {@link TrophyApi.NotFoundError}
     * @throws {@link TrophyApi.UnprocessableEntityError}
     *
     * @example
     *     await trophyApi.admin.points.triggers.get("550e8400-e29b-41d4-a716-446655440000", "660f9500-f30c-42e5-b827-557766550001")
     */
    get(systemId: string, id: string, requestOptions?: Triggers.RequestOptions): Promise<TrophyApi.AdminPointsTrigger>;
}
