/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         user: {
 *             email: "user@example.com",
 *             tz: "Europe/London",
 *             id: "18"
 *         },
 *         value: 750
 *     }
 */
export interface MetricsEventRequest {
    /** The user that triggered the event. */
    user: TrophyApi.UpsertedUser;
    /** The value to add to the user's current total for the given metric. */
    value: number;
}
