/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TrophyApi from "../../../..";
/**
 * @example
 *     {
 *         idempotencyKey: "e4296e4b-8493-4bd1-9c30-5a1a9ac4d78f",
 *         user: {
 *             email: "user@example.com",
 *             name: "User",
 *             tz: "Europe/London",
 *             deviceTokens: ["token1", "token2"],
 *             subscribeToEmails: true,
 *             attributes: {
 *                 "department": "engineering",
 *                 "role": "developer"
 *             },
 *             id: "18"
 *         },
 *         value: 750,
 *         attributes: {
 *             "category": "writing",
 *             "source": "mobile-app"
 *         }
 *     }
 */
export interface MetricsEventRequest {
    /**
     * The idempotency key for the event.
     */
    idempotencyKey?: string;
    /** The user that triggered the event. */
    user: TrophyApi.UpsertedUser;
    /** The value to add to the user's current total for the given metric. */
    value: number;
    /** Event attributes as key-value pairs. Keys must match existing event attributes set up in the Trophy dashboard. */
    attributes?: Record<string, string>;
}
