/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as TrophyApi from "../../../../api";
import * as core from "../../../../core";
export declare const UsersPointsEventSummaryRequestAggregation: core.serialization.Schema<serializers.UsersPointsEventSummaryRequestAggregation.Raw, TrophyApi.UsersPointsEventSummaryRequestAggregation>;
export declare namespace UsersPointsEventSummaryRequestAggregation {
    type Raw = "daily" | "weekly" | "monthly";
}
