/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface LevelsDeleteRequest {
    /**
     * Comma-separated list of level UUIDs to delete.
     */
    ids?: string | string[];
}
