/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../..";
import * as TrophyApi from "../../../../../../../../../api";
import * as core from "../../../../../../../../../core";
export declare const CreateStreakFreezesRequest: core.serialization.Schema<serializers.admin.streaks.CreateStreakFreezesRequest.Raw, TrophyApi.admin.streaks.CreateStreakFreezesRequest>;
export declare namespace CreateStreakFreezesRequest {
    interface Raw {
        freezes: serializers.admin.streaks.CreateStreakFreezesRequestFreezesItem.Raw[];
    }
}
