/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as TrophyApi from "../../../../api";
import * as core from "../../../../core";
export declare const StreaksRankingsRequestType: core.serialization.Schema<serializers.StreaksRankingsRequestType.Raw, TrophyApi.StreaksRankingsRequestType>;
export declare namespace StreaksRankingsRequestType {
    type Raw = "active" | "longest";
}
