/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as TrophyApi from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const RestoreStreaksRequestUsersItem: core.serialization.ObjectSchema<serializers.admin.RestoreStreaksRequestUsersItem.Raw, TrophyApi.admin.RestoreStreaksRequestUsersItem>;
export declare namespace RestoreStreaksRequestUsersItem {
    interface Raw {
        id: string;
    }
}
