/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as TrophyApi from "..";
export declare class ForbiddenError extends errors.TrophyApiError {
    constructor(body: TrophyApi.ErrorBody);
}
