"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PointsClient = void 0;
const BaseClient_1 = require("../../../../../../BaseClient");
const Client_1 = require("../resources/boosts/client/Client");
const Client_2 = require("../resources/levels/client/Client");
const Client_3 = require("../resources/systems/client/Client");
const Client_4 = require("../resources/triggers/client/Client");
class PointsClient {
    constructor(options) {
        this._options = (0, BaseClient_1.normalizeClientOptionsWithAuth)(options);
    }
    get systems() {
        var _a;
        return ((_a = this._systems) !== null && _a !== void 0 ? _a : (this._systems = new Client_3.SystemsClient(this._options)));
    }
    get boosts() {
        var _a;
        return ((_a = this._boosts) !== null && _a !== void 0 ? _a : (this._boosts = new Client_1.BoostsClient(this._options)));
    }
    get levels() {
        var _a;
        return ((_a = this._levels) !== null && _a !== void 0 ? _a : (this._levels = new Client_2.LevelsClient(this._options)));
    }
    get triggers() {
        var _a;
        return ((_a = this._triggers) !== null && _a !== void 0 ? _a : (this._triggers = new Client_4.TriggersClient(this._options)));
    }
}
exports.PointsClient = PointsClient;
