/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as TrophyApi from "../../../../api";
import * as core from "../../../../core";
export declare const Response: core.serialization.Schema<serializers.users.metricEventSummary.Response.Raw, TrophyApi.UsersMetricEventSummaryResponseItem[]>;
export declare namespace Response {
    type Raw = serializers.UsersMetricEventSummaryResponseItem.Raw[];
}
