/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         userIds: ["user-123", "user-456"]
 *     }
 *
 * @example
 *     {
 *         userIds: ["user-123", "user-456"]
 *     }
 *
 * @example
 *     {
 *         userIds: ["user-123", "user-456"]
 *     }
 */
export interface RestoreStreaksRequest {
    /** Array of user IDs to restore streaks for. Maximum 100 users per request. */
    userIds: string[];
}
