"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LeaderboardsAllResponseItemStatus = void 0;
exports.LeaderboardsAllResponseItemStatus = {
    Active: "active",
    Scheduled: "scheduled",
    Finished: "finished",
};
