/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as TrophyApi from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const CreateStreakFreezesRequestFreezesItem: core.serialization.ObjectSchema<serializers.admin.streaks.CreateStreakFreezesRequestFreezesItem.Raw, TrophyApi.admin.streaks.CreateStreakFreezesRequestFreezesItem>;
export declare namespace CreateStreakFreezesRequestFreezesItem {
    interface Raw {
        userId: string;
    }
}
