/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         offset: 1,
 *         limit: 1,
 *         run: "2025-01-15",
 *         userId: "user-123",
 *         userAttributes: "city:London"
 *     }
 */
export interface LeaderboardsGetRequest {
    /**
     * Number of rankings to skip for pagination.
     */
    offset?: number;
    /**
     * Maximum number of rankings to return.
     */
    limit?: number;
    /**
     * Specific run date in YYYY-MM-DD format. If not provided, returns the current run.
     */
    run?: string;
    /**
     * When provided, offset is relative to this user's position on the leaderboard. If the user is not found in the leaderboard, returns empty rankings array.
     */
    userId?: string;
    /**
     * Attribute key and value to filter the rankings by, separated by a colon. This parameter is required, and only valid for leaderboards with a breakdown attribute.
     */
    userAttributes?: string;
}
