/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UsersMetricEventSummaryRequestAggregation = "daily" | "weekly" | "monthly";
export declare const UsersMetricEventSummaryRequestAggregation: {
    readonly Daily: "daily";
    readonly Weekly: "weekly";
    readonly Monthly: "monthly";
};
