/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UsersMetricEventSummaryResponseItem {
    /** The date of the data point. For weekly or monthly aggregations, this is the first date of the period. */
    date: string;
    /** The user's total for this metric at the end of this date. */
    total: number;
    /** The change in the user's total for this metric during this period. */
    change: number;
}
