/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         userAttributes: "plan-type:premium,region:us-east"
 *     }
 */
export interface PointsSummaryRequest {
    /**
     * Optional colon-delimited user attribute filters in the format attributeKey:value,attributeKey:value. Only users matching ALL specified attributes will be included in the points breakdown.
     */
    userAttributes?: string;
}
