/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface BoostsBatchArchiveRequest {
    /**
     * A list of up to 100 boost IDs.
     */
    ids?: string | string[];
}
