/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface BoostsBatchDeleteRequest {
    /**
     * Array of boost UUIDs to archive. Maximum 1000 IDs per request.
     */
    ids?: string | string[];
}
