/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         limit: 1,
 *         skip: 1
 *     }
 */
export interface AttributesListRequest {
    /**
     * Number of records to return.
     */
    limit?: number;
    /**
     * Number of records to skip from the start of the list.
     */
    skip?: number;
}
