/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../..";
import * as TrophyApi from "../../../../../../../api";
import * as core from "../../../../../../../core";
export declare const RestoreStreaksRequest: core.serialization.Schema<serializers.admin.RestoreStreaksRequest.Raw, TrophyApi.admin.RestoreStreaksRequest>;
export declare namespace RestoreStreaksRequest {
    interface Raw {
        users: serializers.admin.RestoreStreaksRequestUsersItem.Raw[];
    }
}
